// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: AgentRequirementResult
/// Source: ..\..\..\..\..\sdk\js\src\v2\gen\types.gen.ts
/// </summary>
public class AgentRequirementResult
{
    [JsonProperty("agent")]
    public string Agent { get; set; }
    [JsonProperty("directory")]
    public string Directory { get; set; }
    [JsonProperty("enabled", NullValueHandling = NullValueHandling.Ignore)]
    public object? Enabled { get; set; }
    [JsonProperty("state", NullValueHandling = NullValueHandling.Ignore)]
    public object? State { get; set; }
    [JsonProperty("skills")]
    public object Skills { get; set; }
    [JsonProperty("mcps")]
    public object Mcps { get; set; }
    [JsonProperty("vscode_extensions")]
    public object Vscode_extensions { get; set; }
    [JsonProperty("error", NullValueHandling = NullValueHandling.Ignore)]
    public object? Error { get; set; }
}
