// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: DiffImage
/// Source: agent-manager.ts
/// </summary>
public class DiffImage
{
    [JsonProperty("before", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | DiffImageSide
    public DiffImageSide? Before { get; set; }
    [JsonProperty("after", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | DiffImageSide
    public DiffImageSide? After { get; set; }
}
