// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: DocumentType
/// Source: ..\..\..\..\..\kilo-visualstudio\tools\webview-contract-extractor\node_modules\typescript\lib\lib.dom.d.ts
/// </summary>
/// <remarks>
/// This type is from TypeScript lib definitions (node_modules/typescript).
/// It is included because it is referenced by a message property.
/// </remarks>

public class DocumentType
{
    [JsonProperty("name")]
    public string Name { get; set; }
    [JsonProperty("ownerDocument")]
    public Document OwnerDocument { get; set; }
    [JsonProperty("publicId")]
    public string PublicId { get; set; }
    [JsonProperty("systemId")]
    public string SystemId { get; set; }
}
