//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: EventTuiToastShow2
/// Source: sdk/js/src/v2/gen/types.gen.ts
/// </summary>
public class EventTuiToastShow2
{
    [JsonProperty("type")]
    public object Type { get; set; }
    [JsonProperty("properties")]
    public object Properties { get; set; }
}
