// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: ExternalWorktreeItem
/// Source: ..\..\..\..\src\agent-manager\WorktreeManager.ts
/// </summary>
public class ExternalWorktreeItem
{
    [JsonProperty("path")]
    public string Path { get; set; }
    [JsonProperty("branch")]
    public string Branch { get; set; }
}
