// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: HTMLElement
/// Source: ..\..\..\..\..\kilo-visualstudio\tools\webview-contract-extractor\node_modules\typescript\lib\lib.dom.d.ts
/// </summary>
/// <remarks>
/// This type is from TypeScript lib definitions (node_modules/typescript).
/// It is included because it is referenced by a message property.
/// </remarks>

public class HTMLElement
{
    [JsonProperty("accessKey")]
    public string AccessKey { get; set; }
    [JsonProperty("accessKeyLabel")]
    public string AccessKeyLabel { get; set; }
    [JsonProperty("autocapitalize")]
    public string Autocapitalize { get; set; }
    [JsonProperty("autocorrect")]
    // Original TypeScript type: literal
    public string Autocorrect { get; set; }
    [JsonProperty("dir")]
    public string Dir { get; set; }
    [JsonProperty("draggable")]
    // Original TypeScript type: literal
    public string Draggable { get; set; }
    [JsonProperty("hidden")]
    // Original TypeScript type: literal
    public string Hidden { get; set; }
    [JsonProperty("inert")]
    // Original TypeScript type: literal
    public string Inert { get; set; }
    [JsonProperty("innerText")]
    public string InnerText { get; set; }
    [JsonProperty("lang")]
    public string Lang { get; set; }
    [JsonProperty("offsetHeight")]
    public double OffsetHeight { get; set; }
    [JsonProperty("offsetLeft")]
    public double OffsetLeft { get; set; }
    [JsonProperty("offsetParent", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: null | Element
    public Element? OffsetParent { get; set; }
    [JsonProperty("offsetTop")]
    public double OffsetTop { get; set; }
    [JsonProperty("offsetWidth")]
    public double OffsetWidth { get; set; }
    [JsonProperty("outerText")]
    public string OuterText { get; set; }
    [JsonProperty("popover", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: null | string
    public string? Popover { get; set; }
    [JsonProperty("spellcheck")]
    // Original TypeScript type: literal
    public string Spellcheck { get; set; }
    [JsonProperty("title")]
    public string Title { get; set; }
    [JsonProperty("translate")]
    // Original TypeScript type: literal
    public string Translate { get; set; }
    [JsonProperty("writingSuggestions")]
    public string WritingSuggestions { get; set; }
}
