// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: HTMLOptionsCollection
/// Source: ..\..\..\..\..\kilo-visualstudio\tools\webview-contract-extractor\node_modules\typescript\lib\lib.dom.d.ts
/// </summary>
/// <remarks>
/// This type is from TypeScript lib definitions (node_modules/typescript).
/// It is included because it is referenced by a message property.
/// </remarks>

public class HTMLOptionsCollection
{
    [JsonProperty("length")]
    public double Length { get; set; }
    [JsonProperty("selectedIndex")]
    public double SelectedIndex { get; set; }
}
