// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: HTMLScriptElement
/// Source: ..\..\..\..\..\kilo-visualstudio\tools\webview-contract-extractor\node_modules\typescript\lib\lib.dom.d.ts
/// </summary>
/// <remarks>
/// This type is from TypeScript lib definitions (node_modules/typescript).
/// It is included because it is referenced by a message property.
/// </remarks>

public class HTMLScriptElement
{
    [JsonProperty("async")]
    // Original TypeScript type: literal
    public string Async { get; set; }
    [JsonProperty("charset")]
    public string Charset { get; set; }
    [JsonProperty("crossOrigin", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: null | string
    public string? CrossOrigin { get; set; }
    [JsonProperty("defer")]
    // Original TypeScript type: literal
    public string Defer { get; set; }
    [JsonProperty("event")]
    public string Event { get; set; }
    [JsonProperty("fetchPriority")]
    // Original TypeScript type: literal
    public string FetchPriority { get; set; }
    [JsonProperty("htmlFor")]
    public string HtmlFor { get; set; }
    [JsonProperty("integrity")]
    public string Integrity { get; set; }
    [JsonProperty("noModule")]
    // Original TypeScript type: literal
    public string NoModule { get; set; }
    [JsonProperty("referrerPolicy")]
    public string ReferrerPolicy { get; set; }
    [JsonProperty("src")]
    public string Src { get; set; }
    [JsonProperty("text")]
    public string Text { get; set; }
    [JsonProperty("type")]
    public string Type { get; set; }
}
