// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: KeyAlgorithm
/// Source: ..\..\..\..\..\kilo-visualstudio\tools\webview-contract-extractor\node_modules\@types\node\crypto.d.ts
/// </summary>
/// <remarks>
/// This type is from Node.js type definitions (node_modules/@types/node).
/// It is included because it is referenced by a message property.
/// </remarks>

public class KeyAlgorithm
{
    [JsonProperty("name")]
    public string Name { get; set; }
}
