//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: LspStatus
/// Source: sdk/js/src/v2/gen/types.gen.ts
/// </summary>
public class LspStatus
{
    [JsonProperty("id")]
    public string Id { get; set; }
    [JsonProperty("name")]
    public string Name { get; set; }
    [JsonProperty("root")]
    public string Root { get; set; }
    [JsonProperty("status")]
    public object Status { get; set; }
}
