// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: MarketplaceInstalledMetadata
/// Source: ..\marketplace.ts
/// </summary>
public class MarketplaceInstalledMetadata
{
    [JsonProperty("project")]
    // Original TypeScript type: __type
    public object Project { get; set; }
    [JsonProperty("global")]
    // Original TypeScript type: __type
    public object Global { get; set; }
}
