// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: MediaCapabilitiesKeySystemConfiguration
/// Source: ..\..\..\..\..\kilo-visualstudio\tools\webview-contract-extractor\node_modules\typescript\lib\lib.dom.d.ts
/// </summary>
/// <remarks>
/// This type is from TypeScript lib definitions (node_modules/typescript).
/// It is included because it is referenced by a message property.
/// </remarks>

public class MediaCapabilitiesKeySystemConfiguration
{
    [JsonProperty("audio", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | KeySystemTrackConfiguration
    public KeySystemTrackConfiguration? Audio { get; set; }
    [JsonProperty("distinctiveIdentifier", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | "required" | "optional" | "not-allowed"
    public object? DistinctiveIdentifier { get; set; }
    [JsonProperty("initDataType", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? InitDataType { get; set; }
    [JsonProperty("keySystem")]
    public string KeySystem { get; set; }
    [JsonProperty("persistentState", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | "required" | "optional" | "not-allowed"
    public object? PersistentState { get; set; }
    [JsonProperty("sessionTypes", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | Array
    public object? SessionTypes { get; set; }
    [JsonProperty("video", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | KeySystemTrackConfiguration
    public KeySystemTrackConfiguration? Video { get; set; }
}
