// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: Node
/// Source: ..\..\..\..\..\kilo-visualstudio\tools\webview-contract-extractor\node_modules\typescript\lib\lib.dom.d.ts
/// </summary>
/// <remarks>
/// This type is from TypeScript lib definitions (node_modules/typescript).
/// It is included because it is referenced by a message property.
/// </remarks>

public class Node
{
    [JsonProperty("baseURI")]
    public string BaseURI { get; set; }
    [JsonProperty("childNodes")]
    // Original TypeScript type: NodeListOf
    public object ChildNodes { get; set; }
    [JsonProperty("firstChild", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: null | ChildNode
    public object? FirstChild { get; set; }
    [JsonProperty("isConnected")]
    public string IsConnected { get; set; }
    [JsonProperty("lastChild", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: null | ChildNode
    public object? LastChild { get; set; }
    [JsonProperty("nextSibling", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: null | ChildNode
    public object? NextSibling { get; set; }
    [JsonProperty("nodeName")]
    public string NodeName { get; set; }
    [JsonProperty("nodeType")]
    public double NodeType { get; set; }
    [JsonProperty("nodeValue", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: null | string
    public string? NodeValue { get; set; }
    [JsonProperty("ownerDocument", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: null | Document
    public Document? OwnerDocument { get; set; }
    [JsonProperty("parentElement", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: null | HTMLElement
    public HTMLElement? ParentElement { get; set; }
    [JsonProperty("parentNode", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: null | ParentNode
    public ParentNode? ParentNode { get; set; }
    [JsonProperty("previousSibling", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: null | ChildNode
    public object? PreviousSibling { get; set; }
    [JsonProperty("textContent", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: null | string
    public string? TextContent { get; set; }
    [JsonProperty("ELEMENT_NODE")]
    public string ELEMENT_NODE { get; set; }
    [JsonProperty("ATTRIBUTE_NODE")]
    public string ATTRIBUTE_NODE { get; set; }
    [JsonProperty("TEXT_NODE")]
    public string TEXT_NODE { get; set; }
    [JsonProperty("CDATA_SECTION_NODE")]
    public string CDATA_SECTION_NODE { get; set; }
    [JsonProperty("ENTITY_REFERENCE_NODE")]
    public string ENTITY_REFERENCE_NODE { get; set; }
    [JsonProperty("ENTITY_NODE")]
    public string ENTITY_NODE { get; set; }
    [JsonProperty("PROCESSING_INSTRUCTION_NODE")]
    public string PROCESSING_INSTRUCTION_NODE { get; set; }
    [JsonProperty("COMMENT_NODE")]
    public string COMMENT_NODE { get; set; }
    [JsonProperty("DOCUMENT_NODE")]
    public string DOCUMENT_NODE { get; set; }
    [JsonProperty("DOCUMENT_TYPE_NODE")]
    public string DOCUMENT_TYPE_NODE { get; set; }
    [JsonProperty("DOCUMENT_FRAGMENT_NODE")]
    public string DOCUMENT_FRAGMENT_NODE { get; set; }
    [JsonProperty("NOTATION_NODE")]
    public string NOTATION_NODE { get; set; }
    [JsonProperty("DOCUMENT_POSITION_DISCONNECTED")]
    public string DOCUMENT_POSITION_DISCONNECTED { get; set; }
    [JsonProperty("DOCUMENT_POSITION_PRECEDING")]
    public string DOCUMENT_POSITION_PRECEDING { get; set; }
    [JsonProperty("DOCUMENT_POSITION_FOLLOWING")]
    public string DOCUMENT_POSITION_FOLLOWING { get; set; }
    [JsonProperty("DOCUMENT_POSITION_CONTAINS")]
    public string DOCUMENT_POSITION_CONTAINS { get; set; }
    [JsonProperty("DOCUMENT_POSITION_CONTAINED_BY")]
    public string DOCUMENT_POSITION_CONTAINED_BY { get; set; }
    [JsonProperty("DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC")]
    public string DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC { get; set; }
}
