// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: NotebookOutput
/// Source: ..\..\..\..\src\services\notebook\types.ts
/// </summary>
public class NotebookOutput
{
    [JsonProperty("mime")]
    public string Mime { get; set; }
    [JsonProperty("text", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Text { get; set; }
    [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Name { get; set; }
    [JsonProperty("message", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Message { get; set; }
    [JsonProperty("stack", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Stack { get; set; }
    [JsonProperty("omitted", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public object? Omitted { get; set; }
    [JsonProperty("truncated", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public object? Truncated { get; set; }
}
