// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: NotificationAction
/// Source: ..\..\..\..\src\kilo-provider\notifications.ts
/// </summary>
public class NotificationAction
{
    [JsonProperty("actionText")]
    public string ActionText { get; set; }
    [JsonProperty("actionURL")]
    public string ActionURL { get; set; }
}
