// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: SandboxConfig
/// Source: config.ts
/// </summary>
public class SandboxConfig
{
    [JsonProperty("enabled", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public object? Enabled { get; set; }
    [JsonProperty("network", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | "allow" | "deny"
    public object? Network { get; set; }
    [JsonProperty("writable_paths", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | Array
    public object? Writable_paths { get; set; }
    [JsonProperty("allowed_hosts", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | Array
    public object? Allowed_hosts { get; set; }
}
