// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: SlashCommandInfo
/// Source: agents.ts
/// </summary>
public class SlashCommandInfo
{
    [JsonProperty("name")]
    public string Name { get; set; }
    [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Description { get; set; }
    [JsonProperty("source", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | "command" | "mcp" | "skill"
    public object? Source { get; set; }
    [JsonProperty("hints")]
    public List<string> Hints { get; set; }
}
