// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: SVGLength
/// Source: ..\..\..\..\..\kilo-visualstudio\tools\webview-contract-extractor\node_modules\typescript\lib\lib.dom.d.ts
/// </summary>
/// <remarks>
/// This type is from TypeScript lib definitions (node_modules/typescript).
/// It is included because it is referenced by a message property.
/// </remarks>

public class SVGLength
{
    [JsonProperty("unitType")]
    public double UnitType { get; set; }
    [JsonProperty("value")]
    public double Value { get; set; }
    [JsonProperty("valueAsString")]
    public string ValueAsString { get; set; }
    [JsonProperty("valueInSpecifiedUnits")]
    public double ValueInSpecifiedUnits { get; set; }
    [JsonProperty("SVG_LENGTHTYPE_UNKNOWN")]
    public string SVG_LENGTHTYPE_UNKNOWN { get; set; }
    [JsonProperty("SVG_LENGTHTYPE_NUMBER")]
    public string SVG_LENGTHTYPE_NUMBER { get; set; }
    [JsonProperty("SVG_LENGTHTYPE_PERCENTAGE")]
    public string SVG_LENGTHTYPE_PERCENTAGE { get; set; }
    [JsonProperty("SVG_LENGTHTYPE_EMS")]
    public string SVG_LENGTHTYPE_EMS { get; set; }
    [JsonProperty("SVG_LENGTHTYPE_EXS")]
    public string SVG_LENGTHTYPE_EXS { get; set; }
    [JsonProperty("SVG_LENGTHTYPE_PX")]
    public string SVG_LENGTHTYPE_PX { get; set; }
    [JsonProperty("SVG_LENGTHTYPE_CM")]
    public string SVG_LENGTHTYPE_CM { get; set; }
    [JsonProperty("SVG_LENGTHTYPE_MM")]
    public string SVG_LENGTHTYPE_MM { get; set; }
    [JsonProperty("SVG_LENGTHTYPE_IN")]
    public string SVG_LENGTHTYPE_IN { get; set; }
    [JsonProperty("SVG_LENGTHTYPE_PT")]
    public string SVG_LENGTHTYPE_PT { get; set; }
    [JsonProperty("SVG_LENGTHTYPE_PC")]
    public string SVG_LENGTHTYPE_PC { get; set; }
}
