//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: TuiConfigGetData
/// Source: sdk/js/src/v2/gen/types.gen.ts
/// </summary>
public class TuiConfigGetData
{
    [JsonProperty("body", NullValueHandling = NullValueHandling.Ignore)]
    public object? Body { get; set; }
    [JsonProperty("path", NullValueHandling = NullValueHandling.Ignore)]
    public object? Path { get; set; }
    [JsonProperty("query", NullValueHandling = NullValueHandling.Ignore)]
    public object? Query { get; set; }
    [JsonProperty("url")]
    public object Url { get; set; }
}
