// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: WorktreeStats
/// Source: ..\..\..\..\src\agent-manager\GitStatsPoller.ts
/// </summary>
public class WorktreeStats
{
    [JsonProperty("worktreeId")]
    public string WorktreeId { get; set; }
    [JsonProperty("files")]
    public double Files { get; set; }
    [JsonProperty("additions")]
    public double Additions { get; set; }
    [JsonProperty("deletions")]
    public double Deletions { get; set; }
    [JsonProperty("ahead")]
    public double Ahead { get; set; }
    [JsonProperty("behind")]
    public double Behind { get; set; }
}
