// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

/// <summary>
/// Type: Worktree (placeholder for typeAlias)
/// Source: ..\..\..\..\src\agent-manager\worktree-importer.ts
/// </summary>
public class Worktree { }
