// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: WorkStyleConfig
/// Source: ..\..\..\..\src\shared\work-style-presets.ts
/// </summary>
public class WorkStyleConfig
{
    [JsonProperty("permission", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Permission { get; set; }
    [JsonProperty("terminal_command_display", NullValueHandling = NullValueHandling.Ignore)]
    public ExpandedCollapsed? Terminal_command_display { get; set; }
    [JsonProperty("auto_collapse_reasoning", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public bool? Auto_collapse_reasoning { get; set; }
}
