//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.KiloConfig;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: IndexingConfig
/// Source: config.ts
/// </summary>
public partial class IndexingConfig : IWebviewMessage
{
    [JsonProperty("enabled", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public bool? Enabled { get; set; }
    [JsonProperty("provider", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: IndexingProvider
    public IndexingProviderEnum? Provider { get; set; }
    [JsonProperty("model", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | null | string
    public string? Model { get; set; }
    [JsonProperty("dimension", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | null | number
    public double? Dimension { get; set; }
    [JsonProperty("vectorStore", NullValueHandling = NullValueHandling.Ignore)]
    public LancedbQdrantEnum? VectorStore { get; set; }
    [JsonProperty("kilo", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: IndexingConfigKiloType
    public IndexingConfigKiloType? Kilo { get; set; }
    [JsonProperty("openai", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: IndexingConfigOpenaiType
    public IndexingConfigOpenaiType? Openai { get; set; }
    [JsonProperty("ollama", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: IndexingConfigOllamaType
    public IndexingConfigOllamaType? Ollama { get; set; }
    [JsonProperty("openai-compatible", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: IndexingConfigOpenaiCompatibleType
    public IndexingConfigOpenaiCompatibleType? OpenaiCompatible { get; set; }
    [JsonProperty("gemini", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: IndexingConfigOpenaiType
    public IndexingConfigOpenaiType? Gemini { get; set; }
    [JsonProperty("mistral", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: IndexingConfigOpenaiType
    public IndexingConfigOpenaiType? Mistral { get; set; }
    [JsonProperty("vercel-ai-gateway", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: IndexingConfigOpenaiType
    public IndexingConfigOpenaiType? VercelAiGateway { get; set; }
    [JsonProperty("bedrock", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: IndexingConfigBedrockType
    public IndexingConfigBedrockType? Bedrock { get; set; }
    [JsonProperty("openrouter", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: IndexingConfigOpenrouterType
    public IndexingConfigOpenrouterType? Openrouter { get; set; }
    [JsonProperty("voyage", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: IndexingConfigOpenaiType
    public IndexingConfigOpenaiType? Voyage { get; set; }
    [JsonProperty("qdrant", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: IndexingConfigQdrantType
    public IndexingConfigQdrantType? Qdrant { get; set; }
    [JsonProperty("lancedb", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: IndexingConfigLancedbType
    public IndexingConfigLancedbType? Lancedb { get; set; }
    [JsonProperty("searchMinScore", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? SearchMinScore { get; set; }
    [JsonProperty("searchMaxResults", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? SearchMaxResults { get; set; }
    [JsonProperty("embeddingBatchSize", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? EmbeddingBatchSize { get; set; }
    [JsonProperty("scannerMaxBatchRetries", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? ScannerMaxBatchRetries { get; set; }
    [JsonProperty("fileExtensions", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | Array
    public object? FileExtensions { get; set; }
}
