//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.KiloConfig;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: IndexingConfigLancedbType
/// Source: config.ts
/// Signature hash: 80f57c22514a677be6f92038f704461ed104bdb420707c14aad22fca4c7db8b5
/// </summary>
public partial class IndexingConfigLancedbType : IWebviewMessage
{
    [JsonProperty("directory", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Directory { get; set; }
}
