// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.KiloConfig;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

/// <summary>
/// Enum: IndexingProviderEnum
/// Generated from union type
/// </summary>
[JsonConverter(typeof(StringEnumConverter))]
public enum IndexingProviderEnum
{
    [JsonProperty("kilo")]
    Kilo,
    [JsonProperty("openai")]
    Openai,
    [JsonProperty("ollama")]
    Ollama,
    [JsonProperty("openai-compatible")]
    OpenaiCompatible,
    [JsonProperty("gemini")]
    Gemini,
    [JsonProperty("mistral")]
    Mistral,
    [JsonProperty("vercel-ai-gateway")]
    VercelAiGateway,
    [JsonProperty("bedrock")]
    Bedrock,
    [JsonProperty("openrouter")]
    Openrouter,
    [JsonProperty("voyage")]
    Voyage
}
