//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.KiloConfig;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: IndexingConfigQdrantType
/// Source: config.ts
/// Signature hash: 425d732f658065a80c19e968640fdbdb4aabf9ec10ba19d265a600a1c1a01375
/// </summary>
public partial class IndexingConfigQdrantType
{
    [JsonProperty("url", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Url { get; set; }
    [JsonProperty("apiKey", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? ApiKey { get; set; }
}
