//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.KiloConfig;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: IndexingConfigOpenaiCompatibleType
/// Source: config.ts
/// Signature hash: 1591a8bd05b17b9d65f757f9a1f5f8fb66dbfa61afeb6333f6095edbe132fac4
/// </summary>
public partial class IndexingConfigOpenaiCompatibleType
{
    [JsonProperty("baseUrl", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? BaseUrl { get; set; }
    [JsonProperty("apiKey", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? ApiKey { get; set; }
}
