//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.KiloConfig;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: KiloEmbeddingModelModelsItemType
/// Source: config.ts
/// Signature hash: 87aa14671d6b4694415d7908b2e6b0cf6a661018a6057a570f634a039f02ff92
/// </summary>
public partial class KiloEmbeddingModelModelsItemType : IWebviewMessage
{
    [JsonProperty("id")]
    public string Id { get; set; }
    [JsonProperty("name")]
    public string Name { get; set; }
    [JsonProperty("dimension")]
    public double Dimension { get; set; }
    [JsonProperty("scoreThreshold")]
    public double ScoreThreshold { get; set; }
    [JsonProperty("note", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Note { get; set; }
}
