//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.KiloConfig;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: kiloType
/// Source: config.ts
/// </summary>
public class KiloType
{
    [JsonProperty("apiKey", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? ApiKey { get; set; }
    [JsonProperty("baseUrl", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? BaseUrl { get; set; }
    [JsonProperty("organizationId", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? OrganizationId { get; set; }
}
