//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Permissions;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: PermissionPatchFile
/// Source: permissions.ts
/// </summary>
public class PermissionPatchFile
{
    [JsonProperty("filePath", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? FilePath { get; set; }
    [JsonProperty("relativePath", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? RelativePath { get; set; }
    [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
    public AddUpdateDeleteMoveEnum? Type { get; set; }
    [JsonProperty("patch", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Patch { get; set; }
    [JsonProperty("additions", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? Additions { get; set; }
    [JsonProperty("deletions", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? Deletions { get; set; }
    [JsonProperty("movePath", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? MovePath { get; set; }
}
