//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Permissions;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: PermissionRequest
/// Source: permissions.ts
/// </summary>
public partial class PermissionRequest
{
    [JsonProperty("id")]
    public string Id { get; set; }
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
    [JsonProperty("toolName")]
    public string ToolName { get; set; }
    [JsonProperty("patterns")]
    public List<string> Patterns { get; set; }
    [JsonProperty("always")]
    public List<string> Always { get; set; }
    [JsonProperty("args")]
    // Original TypeScript type: Record<string, unknown> & { rules?: string[] | undefined; diff?: string | undefined; filepath?: string | undefined; filediff?: PermissionFileDiff | undefined; files?: PermissionPatchFile[] | undefined; description?: string | undefined; heredoc?: boolean | undefined; }
    public object Args { get; set; }
    [JsonProperty("message", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Message { get; set; }
    [JsonProperty("tool", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: PermissionRequestToolType
    public object? Tool { get; set; }
}
