//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Permissions;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: PermissionFileDiff
/// Source: permissions.ts
/// </summary>
public partial class PermissionFileDiff : IWebviewMessage
{
    [JsonProperty("file")]
    public string File { get; set; }
    [JsonProperty("patch", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Patch { get; set; }
    [JsonProperty("additions")]
    public double Additions { get; set; }
    [JsonProperty("deletions")]
    public double Deletions { get; set; }
}
