//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.KiloConfig;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: IndexingConfig
/// Source: config.ts
/// </summary>
public class IndexingConfig
{
    [JsonProperty("enabled", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public bool? Enabled { get; set; }
    [JsonProperty("provider", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: IndexingProvider
    public IndexingProvider? Provider { get; set; }
    [JsonProperty("model", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | null | string
    public string? Model { get; set; }
    [JsonProperty("dimension", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | null | number
    public double? Dimension { get; set; }
    [JsonProperty("vectorStore", NullValueHandling = NullValueHandling.Ignore)]
    public LancedbQdrantEnum? VectorStore { get; set; }
    [JsonProperty("kilo", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Kilo { get; set; }
    [JsonProperty("openai", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Openai { get; set; }
    [JsonProperty("ollama", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Ollama { get; set; }
    [JsonProperty("openai-compatible", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? OpenaiCompatible { get; set; }
    [JsonProperty("gemini", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Gemini { get; set; }
    [JsonProperty("mistral", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Mistral { get; set; }
    [JsonProperty("vercel-ai-gateway", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? VercelAiGateway { get; set; }
    [JsonProperty("bedrock", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Bedrock { get; set; }
    [JsonProperty("openrouter", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Openrouter { get; set; }
    [JsonProperty("voyage", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Voyage { get; set; }
    [JsonProperty("qdrant", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Qdrant { get; set; }
    [JsonProperty("lancedb", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Lancedb { get; set; }
    [JsonProperty("searchMinScore", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? SearchMinScore { get; set; }
    [JsonProperty("searchMaxResults", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? SearchMaxResults { get; set; }
    [JsonProperty("embeddingBatchSize", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? EmbeddingBatchSize { get; set; }
    [JsonProperty("scannerMaxBatchRetries", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? ScannerMaxBatchRetries { get; set; }
    [JsonProperty("fileExtensions", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | Array
    public object? FileExtensions { get; set; }
}
