// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.KiloConfig;

using KiloVisualStudioExtension.ApiClient;
/// <summary>
/// Type: SdkIndexingStatus (alias for IndexingStatus)
/// Source: config.ts
/// </summary>
public class SdkIndexingStatus : ApiClient.IndexingStatus { }
