// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Memory;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.ExtensionMessages;

/// <summary>
/// WebView message: MemoryOperationResultMessage
/// Discriminator: type = "memoryOperationResult"
/// Source: memory.ts
/// Signature hash: b87ab4bef2f31ebde54ca96c3326522ebffc8b6fb86fb27ccf260412b68b9fac
/// </summary>
public class MemoryOperationResultMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "memoryOperationResult";
    [JsonProperty("operation")]
    // Original TypeScript type: MemoryResultOperation
    public MemoryResultOperationEnum Operation { get; set; }
    [JsonProperty("sessionID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? SessionID { get; set; }
    [JsonProperty("ok")]
    public bool Ok { get; set; }
    [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Status { get; set; }
    [JsonProperty("result", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: MemoryOperationResponse
    public object? Result { get; set; }
    [JsonProperty("error", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Error { get; set; }
}
