// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Memory;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

/// <summary>
/// Enum: MemoryOperationEnum
/// Generated from union type
/// </summary>
[JsonConverter(typeof(StringEnumConverter))]
public enum MemoryOperationEnum
{
    [JsonProperty("auto")]
    Auto,
    [JsonProperty("status")]
    Status,
    [JsonProperty("enable")]
    Enable,
    [JsonProperty("inspect")]
    Inspect,
    [JsonProperty("disable")]
    Disable,
    [JsonProperty("rebuild")]
    Rebuild,
    [JsonProperty("remember")]
    Remember,
    [JsonProperty("correct")]
    Correct,
    [JsonProperty("forget")]
    Forget,
    [JsonProperty("purge")]
    Purge
}
