// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Memory;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.ExtensionMessages;

/// <summary>
/// WebView message: MemoryEventMessage
/// Discriminator: type = "memoryEvent"
/// Source: memory.ts
/// Signature hash: 81139890b7353fbf56b131d40075ea467291bc3e6f8a13c42cb4d482a946d841
/// </summary>
public partial class MemoryEventMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "memoryEvent";
    [JsonProperty("sessionID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? SessionID { get; set; }
    [JsonProperty("detail")]
    // Original TypeScript type: MemoryEventDetail
    public MemoryEventDetail Detail { get; set; }
}
