// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.Types;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: AgentMarketplaceItem
/// Discriminator: type = "agent"
/// Source: ..\marketplace.ts
/// </summary>
public class AgentMarketplaceItem
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agent";
    [JsonProperty("content")]
    // Original TypeScript type: AgentContent
    public AgentContent Content { get; set; }
}
