// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: AgentManagerWorktreeDiffLoadingMessage
/// Discriminator: type = "agentManager.worktreeDiffLoading"
/// Source: extension-messages.ts
/// </summary>
public class AgentManagerWorktreeDiffLoadingMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.worktreeDiffLoading";
    [JsonProperty("sessionId")]
    public string SessionId { get; set; }
    [JsonProperty("loading")]
    // Original TypeScript type: literal
    public string Loading { get; set; }
}
