// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.extensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloVisualStudioExtension.WebView.Generated.config;

/// <summary>
/// WebView message: BrowserSettingsLoadedMessage
/// Discriminator: type = "browserSettingsLoaded"
/// Source: extension-messages.ts
/// </summary>
public class BrowserSettingsLoadedMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "browserSettingsLoaded";
    [JsonProperty("settings")]
    // Original TypeScript type: BrowserSettings
    public BrowserSettings Settings { get; set; }
}
