// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.extensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ModelSelectionsLoadedMessage
/// Discriminator: type = "modelSelectionsLoaded"
/// Source: extension-messages.ts
/// </summary>
public class ModelSelectionsLoadedMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "modelSelectionsLoaded";
    [JsonProperty("selections")]
    // Original TypeScript type: __type
    public object Selections { get; set; }
}
