// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: NavigateMessage
/// Discriminator: type = "navigate"
/// Source: extension-messages.ts
/// </summary>
public class NavigateMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "navigate";
    [JsonProperty("view", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: settings | newTask | marketplace | history | profile | subAgentViewer
    public object? View { get; set; }
    [JsonProperty("tab", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Tab { get; set; }
}
