// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.extensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloVisualStudioExtension.WebView.Generated.providers;

/// <summary>
/// WebView message: ProvidersLoadedMessage
/// Discriminator: type = "providersLoaded"
/// Source: extension-messages.ts
/// </summary>
public class ProvidersLoadedMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "providersLoaded";
    [JsonProperty("providers")]
    // Original TypeScript type: __type
    public object Providers { get; set; }
    [JsonProperty("connected")]
    public List<string> Connected { get; set; }
    [JsonProperty("defaults")]
    // Original TypeScript type: __type
    public object Defaults { get; set; }
    [JsonProperty("defaultSelection")]
    // Original TypeScript type: ModelSelection
    public ModelSelection DefaultSelection { get; set; }
    [JsonProperty("authMethods")]
    // Original TypeScript type: __type
    public object AuthMethods { get; set; }
    [JsonProperty("authStates")]
    // Original TypeScript type: __type
    public object AuthStates { get; set; }
}
