// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SandboxStatusMessage
/// Discriminator: type = "sandboxStatus"
/// Source: extension-messages.ts
/// </summary>
public class SandboxStatusMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "sandboxStatus";
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
    [JsonProperty("enabled")]
    public bool Enabled { get; set; }
    [JsonProperty("available")]
    public bool Available { get; set; }
    [JsonProperty("reason", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Reason { get; set; }
    [JsonProperty("version")]
    public double Version { get; set; }
    [JsonProperty("directory")]
    public string Directory { get; set; }
    [JsonProperty("revision")]
    public double Revision { get; set; }
    [JsonProperty("requestID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? RequestID { get; set; }
}
