// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SessionForkedMessage
/// Discriminator: type = "sessionForked"
/// Source: extension-messages.ts
/// </summary>
public class SessionForkedMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "sessionForked";
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
    [JsonProperty("forkedFromID")]
    public string ForkedFromID { get; set; }
}
