// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.extensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloVisualStudioExtension.WebView.Generated.sessions;

/// <summary>
/// WebView message: SessionCreatedMessage
/// Discriminator: type = "sessionCreated"
/// Source: extension-messages.ts
/// </summary>
public class SessionCreatedMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "sessionCreated";
    [JsonProperty("session")]
    // Original TypeScript type: SessionInfo
    public SessionInfo Session { get; set; }
    [JsonProperty("draftID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? DraftID { get; set; }
    [JsonProperty("activate", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public bool? Activate { get; set; }
}
