// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.extensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ValidateFilesResultMessage
/// Discriminator: type = "validateFilesResult"
/// Source: extension-messages.ts
/// </summary>
public class ValidateFilesResultMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "validateFilesResult";
    [JsonProperty("id")]
    public string Id { get; set; }
    [JsonProperty("existing")]
    public List<string> Existing { get; set; }
}
