// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloVisualStudioExtension.WebView.Generated;

/// <summary>
/// WebView message: WorkStyleLoadedMessage
/// Discriminator: type = "workStyleLoaded"
/// Source: extension-messages.ts
/// </summary>
public class WorkStyleLoadedMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "workStyleLoaded";
    [JsonProperty("style")]
    // Original TypeScript type: WorkStyleState
    public WorkStyleState Style { get; set; }
}
