//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.Agents;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: AgentRequirementMCP
/// Source: agents.ts
/// </summary>
public class AgentRequirementMCP
{
    [JsonProperty("name")]
    public string Name { get; set; }
    [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: error | ready | missing
    public object? Status { get; set; }
    [JsonProperty("message", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Message { get; set; }
}
