// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ActionMessage
/// Discriminator: type = "action"
/// Source: extension-messages.ts
/// Signature hash: 223128bbacbf8dbaa92659866c11d18a3cc3ec518041902639599c5c578a9314
/// </summary>
public partial class ActionMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "action";
    [JsonProperty("action")]
    public string Action { get; set; }
}
