// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.AgentManager;

/// <summary>
/// WebView message: AgentManagerPRStatusMessage
/// Discriminator: type = "agentManager.prStatus"
/// Source: extension-messages.ts
/// Signature hash: 1324bed4c9c2c1af961141836fac48fe529b4777045f4d8fda6823221d1c5d4a
/// </summary>
public class AgentManagerPRStatusMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.prStatus";
    [JsonProperty("worktreeId")]
    public string WorktreeId { get; set; }
    [JsonProperty("pr", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: null | PRStatus
    public PRStatus? Pr { get; set; }
    [JsonProperty("error", NullValueHandling = NullValueHandling.Ignore)]
    public GhmissingGhauthFetchfailedEnum? Error { get; set; }
}
