// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: AgentManagerRepoInfoMessage
/// Discriminator: type = "agentManager.repoInfo"
/// Source: extension-messages.ts
/// Signature hash: 5e7210a41ef05ea17f4c43877afc9db9de66f8c9a90564990543166854d0f7b3
/// </summary>
public class AgentManagerRepoInfoMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.repoInfo";
    [JsonProperty("branch")]
    public string Branch { get; set; }
    [JsonProperty("defaultBranch", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? DefaultBranch { get; set; }
}
