// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.AgentManager;

/// <summary>
/// WebView message: AgentManagerWorktreeSetupMessage
/// Discriminator: type = "agentManager.worktreeSetup"
/// Source: extension-messages.ts
/// </summary>
public class AgentManagerWorktreeSetupMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.worktreeSetup";
    [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: error | creating | ready | starting
    public object? Status { get; set; }
    [JsonProperty("message")]
    public string Message { get; set; }
    [JsonProperty("sessionId", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? SessionId { get; set; }
    [JsonProperty("branch", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Branch { get; set; }
    [JsonProperty("worktreeId", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? WorktreeId { get; set; }
    [JsonProperty("errorCode", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: WorktreeErrorCode
    public WorktreeErrorCode? ErrorCode { get; set; }
}
