// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.AgentManager;

/// <summary>
/// WebView message: AgentManagerTerminalCreatedMessage
/// Discriminator: type = "agentManager.terminal.created"
/// Source: extension-messages.ts
/// </summary>
public class AgentManagerTerminalCreatedMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.terminal.created";
    [JsonProperty("worktreeId", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: null | string
    public string? WorktreeId { get; set; }
    [JsonProperty("terminalId")]
    public string TerminalId { get; set; }
    [JsonProperty("title")]
    public string Title { get; set; }
    [JsonProperty("wsUrl")]
    public string WsUrl { get; set; }
    [JsonProperty("font")]
    // Original TypeScript type: TerminalFont
    public TerminalFont Font { get; set; }
}
