// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.Agents;

/// <summary>
/// WebView message: AgentRequirementsLoadedMessage
/// Discriminator: type = "agentRequirementsLoaded"
/// Source: extension-messages.ts
/// Signature hash: 82ce29411d042052742586ef92be1d1d50a9cb34e7bd8ae787b64eb05aec64ee
/// </summary>
public class AgentRequirementsLoadedMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentRequirementsLoaded";
    [JsonProperty("result")]
    // Original TypeScript type: AgentRequirementResult
    public AgentRequirementResult Result { get; set; }
}
