// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.AgentManager;

/// <summary>
/// WebView message: AgentManagerBranchesMessage
/// Discriminator: type = "agentManager.branches"
/// Source: extension-messages.ts
/// Signature hash: 4004d45092bc36295ec907bf0a85c5bed6e1420953142e4467b47d937f1170b2
/// </summary>
public class AgentManagerBranchesMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.branches";
    [JsonProperty("branches")]
    public List<BranchInfo> Branches { get; set; }
    [JsonProperty("defaultBranch")]
    public string DefaultBranch { get; set; }
}
