// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: AgentManagerKeybindingsMessage
/// Discriminator: type = "agentManager.keybindings"
/// Source: extension-messages.ts
/// </summary>
public class AgentManagerKeybindingsMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.keybindings";
    [JsonProperty("bindings")]
    // Original TypeScript type: __type
    public object Bindings { get; set; }
}
