// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.AgentManager;

/// <summary>
/// WebView message: AgentManagerTerminalFontChangedMessage
/// Discriminator: type = "agentManager.terminal.fontChanged"
/// Source: extension-messages.ts
/// </summary>
public class AgentManagerTerminalFontChangedMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.terminal.fontChanged";
    [JsonProperty("font")]
    // Original TypeScript type: TerminalFont
    public TerminalFont Font { get; set; }
}
