// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs;

/// <summary>
/// WebView message: AppendReviewCommentsToTerminalMessage
/// Discriminator: type = "appendReviewCommentsToTerminal"
/// Source: extension-messages.ts
/// Signature hash: 53b1be87d48c87b038cfd24eca872b19ac90c66d8cd4e016bb3108c9536f07c4
/// </summary>
public partial class AppendReviewCommentsToTerminalMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "appendReviewCommentsToTerminal";
    [JsonProperty("comments")]
    public List<ReviewCommentData> Comments { get; set; }
    [JsonProperty("autoSend", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public bool? AutoSend { get; set; }
    [JsonProperty("targetTerminalId")]
    public string TargetTerminalId { get; set; }
}
