// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: AppendChatBoxMessage
/// Discriminator: type = "appendChatBoxMessage"
/// Source: extension-messages.ts
/// Signature hash: c7e48cfcba4c61d94b4c1079f59f58f6ec8a60fc9f52c7abc7b8ac484dd0aeea
/// </summary>
public partial class AppendChatBoxMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "appendChatBoxMessage";
    [JsonProperty("text")]
    public string Text { get; set; }
}
