// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: AutocompleteSettingsLoadedMessage
/// Discriminator: type = "autocompleteSettingsLoaded"
/// Source: extension-messages.ts
/// Signature hash: 14ddba67bbe6a2c3bdfedb08bc28bcc5de20f14fd0c1f043728856844c08b3e1
/// </summary>
public class AutocompleteSettingsLoadedMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "autocompleteSettingsLoaded";
    [JsonProperty("settings")]
    // Original TypeScript type: settingsType
    public SettingsType Settings { get; set; }
}
