// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ChatCompletionResultMessage
/// Discriminator: type = "chatCompletionResult"
/// Source: extension-messages.ts
/// Signature hash: 00e0998301bc26b74d107df6bbc8b9d1449596439fd8a19cf6f2f7679cc4d895
/// </summary>
public partial class ChatCompletionResultMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "chatCompletionResult";
    [JsonProperty("text")]
    public string Text { get; set; }
    [JsonProperty("requestId")]
    public string RequestId { get; set; }
}
