//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: ChatSettingsLoadedMessageSettingsType
/// Source: extension-messages.ts
/// Signature hash: 12826a517574c243096adbe5d6d9107054c050dab2dba15a28a71280b494da8b
/// </summary>
public partial class ChatSettingsLoadedMessageSettingsType : IWebviewMessage
{
    [JsonProperty("shiftTabCyclesVariant")]
    public bool ShiftTabCyclesVariant { get; set; }
}
