// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ChatSettingsLoadedMessage
/// Discriminator: type = "chatSettingsLoaded"
/// Source: extension-messages.ts
/// Signature hash: 675b7e4fcbdcf48fe108166914629a2424eec8d959c67155ad1ecdddcef7b884
/// </summary>
public class ChatSettingsLoadedMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "chatSettingsLoaded";
    [JsonProperty("settings")]
    // Original TypeScript type: settingsType
    public SettingsType Settings { get; set; }
}
