// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ClearPendingPromptsMessage
/// Discriminator: type = "clearPendingPrompts"
/// Source: extension-messages.ts
/// Signature hash: d2427c7d18f032b9933a65405fbe96d0523ebe28463f8e505060c6f4177f3f66
/// </summary>
public class ClearPendingPromptsMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "clearPendingPrompts";
}
