// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: CloudSessionImportFailedMessage
/// Discriminator: type = "cloudSessionImportFailed"
/// Source: extension-messages.ts
/// </summary>
public class CloudSessionImportFailedMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "cloudSessionImportFailed";
    [JsonProperty("cloudSessionId")]
    public string CloudSessionId { get; set; }
    [JsonProperty("error")]
    public string Error { get; set; }
}
