// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.Agents;

/// <summary>
/// WebView message: CommandsLoadedMessage
/// Discriminator: type = "commandsLoaded"
/// Source: extension-messages.ts
/// Signature hash: 2567692d00c2d83a0a7cbc162c049740210e9b0ca0cdef9e1383943256fcbc30
/// </summary>
public class CommandsLoadedMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "commandsLoaded";
    [JsonProperty("commands")]
    public List<SlashCommandInfo> Commands { get; set; }
}
