// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.AgentManager;

/// <summary>
/// WebView message: DiffViewerDiffsMessage
/// Discriminator: type = "diffViewer.diffs"
/// Source: extension-messages.ts
/// Signature hash: 1fd763ac3eeebcc1b7c5d466260d2b4b931f0cab3af5c126417ddfccdd759675
/// </summary>
public class DiffViewerDiffsMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "diffViewer.diffs";
    [JsonProperty("diffs")]
    public List<WorktreeFileDiff> Diffs { get; set; }
}
