// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: DiffViewerCapabilitiesMessage
/// Discriminator: type = "diffViewer.capabilities"
/// Source: extension-messages.ts
/// Signature hash: 71790b09ab512f5e56549142b8fef5d84e8f778dde5337c31068a0e67343c559
/// </summary>
public class DiffViewerCapabilitiesMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "diffViewer.capabilities";
    [JsonProperty("capabilities")]
    // Original TypeScript type: DiffSourceCapabilities
    public object Capabilities { get; set; }
}
