// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: DiffViewerRevertFileResultMessage
/// Discriminator: type = "diffViewer.revertFileResult"
/// Source: extension-messages.ts
/// Signature hash: 3ca2eeed34ded09ec300f1809724311301cbfe12c476a1284203964f95395618
/// </summary>
public class DiffViewerRevertFileResultMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "diffViewer.revertFileResult";
    [JsonProperty("file")]
    public string File { get; set; }
    [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: success | error
    public object? Status { get; set; }
    [JsonProperty("message")]
    public string Message { get; set; }
}
