// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: DiffViewerNoticeMessage
/// Discriminator: type = "diffViewer.notice"
/// Source: extension-messages.ts
/// Signature hash: 29708702048bef1135a06b6c8777365aa8d9163fc18a774af6401c0ba9fdf805
/// </summary>
public class DiffViewerNoticeMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "diffViewer.notice";
    [JsonProperty("notice", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | "snapshots-disabled"
    public string? Notice { get; set; }
}
