// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: EnhancePromptErrorMessage
/// Discriminator: type = "enhancePromptError"
/// Source: extension-messages.ts
/// Signature hash: f6ff514674add5643f46ca712330d50028556d2f5fc393c38576c103f9f87647
/// </summary>
public class EnhancePromptErrorMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "enhancePromptError";
    [JsonProperty("error")]
    public string Error { get; set; }
    [JsonProperty("requestId")]
    public string RequestId { get; set; }
}
