//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: errorType
/// Source: extension-messages.ts
/// </summary>
public class ErrorType
{
    [JsonProperty("name")]
    public string Name { get; set; }
    [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Data { get; set; }
}
