//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: ExtensionSettings
/// Source: extension-messages.ts
/// </summary>
public partial class ExtensionSettings
{
    [JsonProperty("maxCost", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? MaxCost { get; set; }
}
