// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.Providers;

/// <summary>
/// WebView message: FavoritesLoadedMessage
/// Discriminator: type = "favoritesLoaded"
/// Source: extension-messages.ts
/// Signature hash: 9b06c5ca7d253d3bccd9881c4ccbffc4d037bb8f910bfce20230cc1a568bcc68
/// </summary>
public class FavoritesLoadedMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "favoritesLoaded";
    [JsonProperty("favorites")]
    public List<ModelSelection> Favorites { get; set; }
}
