//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: filesItemType
/// Source: extension-messages.ts
/// </summary>
public class FilesItemType
{
    [JsonProperty("mime")]
    public string Mime { get; set; }
    [JsonProperty("url")]
    public string Url { get; set; }
}
