// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.Types;

/// <summary>
/// WebView message: FontSizeChangedMessage
/// Discriminator: type = "fontSizeChanged"
/// Source: extension-messages.ts
/// Signature hash: 3c3c38392d336db33c42db9ec75e58baebdcc70008b85acdf5f470cd84f92306
/// </summary>
public partial class FontSizeChangedMessage : IKiloClawOutMessage, IWebviewMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "fontSizeChanged";
    [JsonProperty("fontSize")]
    public double FontSize { get; set; }
}
