//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: IndexingStatusLoadedMessageStatusType
/// Source: extension-messages.ts
/// Signature hash: dc8b6757d5d2415d39f1b69d062dc5e559e205bcf74a06ce024493ed09a1982d
/// </summary>
public partial class IndexingStatusLoadedMessageStatusType : IWebviewMessage
{
    [JsonProperty("state", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: Disabled | In Progress | Complete | Error | Standby
    public object? State { get; set; }
    [JsonProperty("message")]
    public string Message { get; set; }
    [JsonProperty("processedFiles")]
    public double ProcessedFiles { get; set; }
    [JsonProperty("totalFiles")]
    public double TotalFiles { get; set; }
    [JsonProperty("percent")]
    public double Percent { get; set; }
}
