// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.KiloProviderUtils;

/// <summary>
/// WebView message: IndexingStatusLoadedMessage
/// Discriminator: type = "indexingStatusLoaded"
/// Source: extension-messages.ts
/// Signature hash: 62c3da26ba7a0a5260ccdff7d54b0c9ab405dbe63a28bd5000ddba09b34e3848
/// </summary>
public partial class IndexingStatusLoadedMessage : IWebviewMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "indexingStatusLoaded";
    [JsonProperty("status")]
    // Original TypeScript type: IndexingStatusLoadedMessageStatusType
    public IndexingStatusLoadedMessageStatusType Status { get; set; }
}
