// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.KiloProviderUtils;

/// <summary>
/// WebView message: IndexingStatusLoadedMessage
/// Discriminator: type = "indexingStatusLoaded"
/// Source: extension-messages.ts
/// Signature hash: 819198f633d4db8fe7243af2d51221f630b9ba0b4e0f1af993b3bf035e00016d
/// </summary>
public partial class IndexingStatusLoadedMessage : IWebviewMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "indexingStatusLoaded";
    [JsonProperty("status")]
    // Original TypeScript type: __type
    public object Status { get; set; }
}
