// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: IndexingSettingsLoadedMessage
/// Discriminator: type = "indexingSettingsLoaded"
/// Source: extension-messages.ts
/// Signature hash: 16807cf2ae530d01a4a0124dea15f94387228ee3865117ebb30d9ac31258a0c3
/// </summary>
public class IndexingSettingsLoadedMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "indexingSettingsLoaded";
    [JsonProperty("settings")]
    // Original TypeScript type: settingsType
    public SettingsType Settings { get; set; }
}
