// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.Types;
using KiloExtensionDTOs;

/// <summary>
/// WebView message: MarketplaceDataMessage
/// Discriminator: type = "marketplaceData"
/// Source: extension-messages.ts
/// Signature hash: de1d4bac99c05d91d118a93316c4e16ace4ef6d2bba6be39db8d3a8e218d5937
/// </summary>
public class MarketplaceDataMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "marketplaceData";
    [JsonProperty("marketplaceItems")]
    public List<object> MarketplaceItems { get; set; }
    [JsonProperty("marketplaceInstalledMetadata")]
    // Original TypeScript type: MarketplaceInstalledMetadata
    public MarketplaceInstalledMetadata MarketplaceInstalledMetadata { get; set; }
    [JsonProperty("marketplaceRelevance")]
    // Original TypeScript type: __type
    public object MarketplaceRelevance { get; set; }
    [JsonProperty("errors", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | Array
    public object? Errors { get; set; }
    [JsonProperty("showAgentMigrationBanner", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public bool? ShowAgentMigrationBanner { get; set; }
}
