// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: MarketplaceInstallResultMessage
/// Discriminator: type = "marketplaceInstallResult"
/// Source: extension-messages.ts
/// Signature hash: f7e8b249f3a9ffb4210061316d4530bff025d356bc4975b28f41aeb55d4de9f4
/// </summary>
public class MarketplaceInstallResultMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "marketplaceInstallResult";
    [JsonProperty("success")]
    public bool Success { get; set; }
    [JsonProperty("slug")]
    public string Slug { get; set; }
    [JsonProperty("error", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Error { get; set; }
}
