// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: McpStatusLoadedMessage
/// Discriminator: type = "mcpStatusLoaded"
/// Source: extension-messages.ts
/// Signature hash: 7d1bb9b490209eba99694271a63230265f8e5699a2c396f01c784a96b92b7e23
/// </summary>
public class McpStatusLoadedMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "mcpStatusLoaded";
    [JsonProperty("status")]
    // Original TypeScript type: __type
    public object Status { get; set; }
}
