// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.Sessions;
using KiloExtensionDTOs.KiloProviderUtils;

/// <summary>
/// WebView message: MessageCreatedMessage
/// Discriminator: type = "messageCreated"
/// Source: extension-messages.ts
/// Signature hash: 36e7d414838dd1f04ff9311f57c570d29866430181de1a2338e46a189e326df1
/// </summary>
public partial class MessageCreatedMessage : IWebviewMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "messageCreated";
    [JsonProperty("message")]
    // Original TypeScript type: Message
    public Message Message { get; set; }
}
