// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.KiloProviderUtils;

/// <summary>
/// WebView message: MessageRemovedMessage
/// Discriminator: type = "messageRemoved"
/// Source: extension-messages.ts
/// Signature hash: d0bc1a00b15be4b7fec96ad8ef947bc4c820433bd0f3ecf37c4b2fbc745f35ab
/// </summary>
public partial class MessageRemovedMessage : IWebviewMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "messageRemoved";
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
    [JsonProperty("messageID")]
    public string MessageID { get; set; }
}
