// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ModelSelectorExpandedLoadedMessage
/// Discriminator: type = "modelSelectorExpandedLoaded"
/// Source: extension-messages.ts
/// Signature hash: 18320e5789c0710e0cd5a81353220ae84ddb49614afa03c625b81b71dcc49089
/// </summary>
public class ModelSelectorExpandedLoadedMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "modelSelectorExpandedLoaded";
    [JsonProperty("value")]
    public bool Value { get; set; }
}
