// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: NotificationSettingsLoadedMessage
/// Discriminator: type = "notificationSettingsLoaded"
/// Source: extension-messages.ts
/// Signature hash: 166c20f179c220ef49d651e4dff9117931ed466ef25a235463e91e5dd70cf6a7
/// </summary>
public class NotificationSettingsLoadedMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "notificationSettingsLoaded";
    [JsonProperty("settings")]
    // Original TypeScript type: settingsType
    public SettingsType Settings { get; set; }
}
