//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: NotificationSettingsLoadedMessageSettingsType
/// Source: extension-messages.ts
/// Signature hash: f720b636b386859738dde1e2621da00815e91b51cec6252ce2647475f02ddfae
/// </summary>
public partial class NotificationSettingsLoadedMessageSettingsType : IWebviewMessage
{
    [JsonProperty("attentionEnabled")]
    public bool AttentionEnabled { get; set; }
    [JsonProperty("attentionSound")]
    public string AttentionSound { get; set; }
}
