//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs;

/// <summary>
/// Part type: PartsupdatedMessage
/// Discriminator: type = "partsUpdated"
/// Source: extension-messages.ts
/// Signature hash: fafa457b200c456c2a61504d34516ade1639c34ed60f704100f1eae996167c25
/// </summary>
public class PartsupdatedMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "partsUpdated";
    [JsonProperty("updates")]
    public List<UpdatesItemType> Updates { get; set; }
}
