// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.Profile;

/// <summary>
/// WebView message: ProfileDataMessage
/// Discriminator: type = "profileData"
/// Source: extension-messages.ts
/// Signature hash: 7d0149bdefd90035c298d402d1be03c984183d508b90b3c3d9edff05ce7d018c
/// </summary>
public class ProfileDataMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "profileData";
    [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: null | ProfileData
    public ProfileData? Data { get; set; }
}
