// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.Providers;

/// <summary>
/// WebView message: ProvidersLoadedMessage
/// Discriminator: type = "providersLoaded"
/// Source: extension-messages.ts
/// Signature hash: d9a0e5926de8d2192d5974628f62390d2bf94c8cdb1f6e62be6f18e27d07c20d
/// </summary>
public partial class ProvidersLoadedMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "providersLoaded";
    [JsonProperty("providers")]
    // Original TypeScript type: __type
    public object Providers { get; set; }
    [JsonProperty("connected")]
    public List<string> Connected { get; set; }
    [JsonProperty("defaults")]
    // Original TypeScript type: __type
    public object Defaults { get; set; }
    [JsonProperty("defaultSelection")]
    // Original TypeScript type: ModelSelection
    public ModelSelection DefaultSelection { get; set; }
    [JsonProperty("authMethods")]
    // Original TypeScript type: __type
    public object AuthMethods { get; set; }
    [JsonProperty("authStates")]
    // Original TypeScript type: __type
    public object AuthStates { get; set; }
}
