// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: QuestionResolvedMessage
/// Discriminator: type = "questionResolved"
/// Source: extension-messages.ts
/// Signature hash: c6f5a6a188c7bb4a7afb30da1cea02d327dfcab7c9236f3f98bc2de169c21ef5
/// </summary>
public class QuestionResolvedMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "questionResolved";
    [JsonProperty("requestID")]
    public string RequestID { get; set; }
}
