// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.Connection;

/// <summary>
/// WebView message: ReadyMessage
/// Discriminator: type = "ready"
/// Source: extension-messages.ts
/// Signature hash: a9c76a8ed7326cbcc3e9afc0742e1e5ffb0fc412b5da3f254cb6a2a5b6f5b28c
/// </summary>
public class ReadyMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "ready";
    [JsonProperty("serverInfo", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | ServerInfo
    public ServerInfo? ServerInfo { get; set; }
    [JsonProperty("extensionVersion", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? ExtensionVersion { get; set; }
    [JsonProperty("vscodeLanguage", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? VscodeLanguage { get; set; }
    [JsonProperty("languageOverride", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? LanguageOverride { get; set; }
    [JsonProperty("fontSize", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? FontSize { get; set; }
    [JsonProperty("workspaceDirectory", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? WorkspaceDirectory { get; set; }
}
