// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.Providers;

/// <summary>
/// WebView message: RecentsLoadedMessage
/// Discriminator: type = "recentsLoaded"
/// Source: extension-messages.ts
/// Signature hash: b2e1a7bfb6229b78083c86ce6d3a8e480f90a87ac7637a5bf908adafbefcb450
/// </summary>
public class RecentsLoadedMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "recentsLoaded";
    [JsonProperty("recents")]
    public List<ModelSelection> Recents { get; set; }
}
