// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.Sessions;
using KiloExtensionDTOs.KiloProviderUtils;

/// <summary>
/// WebView message: SessionTurnClosedMessage
/// Discriminator: type = "sessionTurnClosed"
/// Source: extension-messages.ts
/// Signature hash: a938740656f57f38c7bcacd3a4aaf00937749fec5eb5bf6d86744eab9f22aaa0
/// </summary>
public partial class SessionTurnClosedMessage : IWebviewMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "sessionTurnClosed";
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
    [JsonProperty("reason")]
    // Original TypeScript type: SessionCloseReason
    public SessionCloseReasonEnum Reason { get; set; }
}
