// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.Sessions;

/// <summary>
/// WebView message: SessionsLoadedMessage
/// Discriminator: type = "sessionsLoaded"
/// Source: extension-messages.ts
/// Signature hash: 462449d3f9f6c572258febf2943d979e706f84dba5c51b0cb523a3842525b5d8
/// </summary>
public class SessionsLoadedMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "sessionsLoaded";
    [JsonProperty("sessions")]
    public List<SessionInfo> Sessions { get; set; }
    [JsonProperty("preserveSessionIds", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | Array
    public object? PreserveSessionIds { get; set; }
}
