// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.KiloProviderUtils;

/// <summary>
/// WebView message: SessionDeletedMessage
/// Discriminator: type = "sessionDeleted"
/// Source: extension-messages.ts
/// Signature hash: 60a0a622c068a0a0f775ee48ccb0704fe6b8c49ca63330939a89d75f5222d97d
/// </summary>
public class SessionDeletedMessage : IWebviewMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "sessionDeleted";
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
}
