// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.Sessions;
using KiloExtensionDTOs.KiloProviderUtils;

/// <summary>
/// WebView message: SessionCreatedMessage
/// Discriminator: type = "sessionCreated"
/// Source: extension-messages.ts
/// Signature hash: b9ac2cefb8b6ae76c73dc35b900602b25e797be2193730e66469ca3983c07019
/// </summary>
public class SessionCreatedMessage : IWebviewMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "sessionCreated";
    [JsonProperty("session")]
    // Original TypeScript type: SessionInfo
    public SessionInfo Session { get; set; }
    [JsonProperty("draftID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? DraftID { get; set; }
    [JsonProperty("activate", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public bool? Activate { get; set; }
}
