// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.Sessions;

/// <summary>
/// WebView message: SessionUpdatedMessage
/// Discriminator: type = "sessionUpdated"
/// Source: extension-messages.ts
/// Signature hash: ce0108fff6e4a3f89b4f147fbe5df6a5566b4e8298660e3269870a6e791446dd
/// </summary>
public class SessionUpdatedMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "sessionUpdated";
    [JsonProperty("session")]
    // Original TypeScript type: SessionUpdate
    public SessionUpdate Session { get; set; }
}
