// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SessionModelUsageLoadedMessage
/// Discriminator: type = "sessionModelUsageLoaded"
/// Source: extension-messages.ts
/// Signature hash: 7acd95bd57405a875333f108c682223c562081deac3f61aa7398b4a3ac73d9e3
/// </summary>
public class SessionModelUsageLoadedMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "sessionModelUsageLoaded";
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
    [JsonProperty("requestID")]
    public string RequestID { get; set; }
    [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Data { get; set; }
}
