// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SessionModelUsageChangedMessage
/// Discriminator: type = "sessionModelUsageChanged"
/// Source: extension-messages.ts
/// Signature hash: 878e4208a40cdef561a7bce94c14f2fc91a9bd06c0d144d384f1e27316d03f75
/// </summary>
public class SessionModelUsageChangedMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "sessionModelUsageChanged";
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
}
