// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.KiloProviderUtils;

/// <summary>
/// WebView message: SessionErrorMessage
/// Discriminator: type = "sessionError"
/// Source: extension-messages.ts
/// Signature hash: 5d87f6e4b5ad474442480c611a79dd72b26a26b20e022c98e9a89e6ef7070fd0
/// </summary>
public class SessionErrorMessage : IWebviewMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "sessionError";
    [JsonProperty("sessionID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? SessionID { get; set; }
    [JsonProperty("error", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: errorType
    public ErrorType? Error { get; set; }
}
