// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SessionCostAlertMessage
/// Discriminator: type = "sessionCostAlert"
/// Source: extension-messages.ts
/// Signature hash: 6176a7943b20e049c040600600bdb824522037d729fac0d551a85712ec8e995d
/// </summary>
public class SessionCostAlertMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "sessionCostAlert";
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
    [JsonProperty("limit")]
    public double Limit { get; set; }
    [JsonProperty("cost")]
    public string Cost { get; set; }
}
