//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: settingsType
/// Source: extension-messages.ts
/// </summary>
public class SettingsType
{
    [JsonProperty("attentionEnabled")]
    public bool AttentionEnabled { get; set; }
    [JsonProperty("attentionSound")]
    public string AttentionSound { get; set; }
}
