// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SpeechToTextResultMessage
/// Discriminator: type = "speechToTextResult"
/// Source: extension-messages.ts
/// Signature hash: 5ea5d445e94e3c47dc1c5644eb28c74898f9e16deb685098921d56c2465898e2
/// </summary>
public partial class SpeechToTextResultMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "speechToTextResult";
    [JsonProperty("text")]
    public string Text { get; set; }
    [JsonProperty("requestId")]
    public string RequestId { get; set; }
}
