// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SuggestionErrorMessage
/// Discriminator: type = "suggestionError"
/// Source: extension-messages.ts
/// Signature hash: 73a649e0c335c43fb38cf191168c9c760189b4440c33f403c86f39c5eba47afa
/// </summary>
public class SuggestionErrorMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "suggestionError";
    [JsonProperty("requestID")]
    public string RequestID { get; set; }
}
