// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: TerminalContextErrorMessage
/// Discriminator: type = "terminalContextError"
/// Source: extension-messages.ts
/// </summary>
public class TerminalContextErrorMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "terminalContextError";
    [JsonProperty("requestId")]
    public string RequestId { get; set; }
    [JsonProperty("error")]
    public string Error { get; set; }
}
