// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: TimelineSettingLoadedMessage
/// Discriminator: type = "timelineSettingLoaded"
/// Source: extension-messages.ts
/// Signature hash: 36b428441e0aaf16355231543bf0dda0fab9168f0c26a5c61afe762773516ed5
/// </summary>
public partial class TimelineSettingLoadedMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "timelineSettingLoaded";
    [JsonProperty("visible")]
    public bool Visible { get; set; }
}
