// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ViewSubAgentSessionMessage
/// Discriminator: type = "viewSubAgentSession"
/// Source: extension-messages.ts
/// Signature hash: 3f2499d0cd6ae15c7e8318bf4c7038e076eaa9d6be313258f83e8fc96ed83c03
/// </summary>
public partial class ViewSubAgentSessionMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "viewSubAgentSession";
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
}
