// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: WorktreeStatsLoadedMessage
/// Discriminator: type = "worktreeStatsLoaded"
/// Source: extension-messages.ts
/// Signature hash: bda1c1463e9daf3cac215efef29fe3eff4ef6204c2216e54689a7e8a392740d2
/// </summary>
public class WorktreeStatsLoadedMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "worktreeStatsLoaded";
    [JsonProperty("files")]
    public double Files { get; set; }
    [JsonProperty("additions")]
    public double Additions { get; set; }
    [JsonProperty("deletions")]
    public double Deletions { get; set; }
}
