// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs;

/// <summary>
/// WebView message: WorkStyleAppliedMessage
/// Discriminator: type = "workStyleApplied"
/// Source: extension-messages.ts
/// Signature hash: 71827858fc19c493b75d85ac7f0e5ab1d4a1a41bfb051836790abc1e94cf3ff2
/// </summary>
public class WorkStyleAppliedMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "workStyleApplied";
    [JsonProperty("style")]
    // Original TypeScript type: WorkStyle
    public WorkStyle Style { get; set; }
}
