// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.webviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: AgentManagerTerminalCreateRequest
/// Discriminator: type = "agentManager.terminal.create"
/// Source: webview-messages.ts
/// </summary>
public class AgentManagerTerminalCreateRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.terminal.create";
    [JsonProperty("worktreeId", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: null | string
    public string? WorktreeId { get; set; }
}
