// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: AuthorizeProviderOAuthMessage
/// Discriminator: type = "authorizeProviderOAuth"
/// Source: webview-messages.ts
/// </summary>
public class AuthorizeProviderOAuthMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "authorizeProviderOAuth";
    [JsonProperty("requestId")]
    public string RequestId { get; set; }
    [JsonProperty("providerID")]
    public string ProviderID { get; set; }
    [JsonProperty("method")]
    public double Method { get; set; }
}
