// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.webviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloVisualStudioExtension.WebView.Generated;

/// <summary>
/// WebView message: FilterMarketplaceItemsMessage
/// Discriminator: type = "filterMarketplaceItems"
/// Source: webview-messages.ts
/// </summary>
public class FilterMarketplaceItemsMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "filterMarketplaceItems";
    [JsonProperty("filters")]
    // Original TypeScript type: MarketplaceFilters
    public MarketplaceFilters Filters { get; set; }
}
