// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.webviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloVisualStudioExtension.WebView.Generated.sessions;

/// <summary>
/// WebView message: LoadMessagesRequest
/// Discriminator: type = "loadMessages"
/// Source: webview-messages.ts
/// </summary>
public class LoadMessagesRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "loadMessages";
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
    [JsonProperty("mode", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: MessageLoadMode
    public MessageLoadMode? Mode { get; set; }
    [JsonProperty("before", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Before { get; set; }
    [JsonProperty("limit", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? Limit { get; set; }
}
