// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SessionCostAlertResponseRequest
/// Discriminator: type = "sessionCostAlertResponse"
/// Source: webview-messages.ts
/// </summary>
public class SessionCostAlertResponseRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "sessionCostAlertResponse";
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
    [JsonProperty("limit")]
    public double Limit { get; set; }
    [JsonProperty("response", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: continue | stop
    public object? Response { get; set; }
}
