// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.webviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: UpdateConfigMessage
/// Discriminator: type = "updateConfig"
/// Source: webview-messages.ts
/// </summary>
public class UpdateConfigMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "updateConfig";
    [JsonProperty("config")]
    // Original TypeScript type: __type
    public object Config { get; set; }
    [JsonProperty("globalUnset", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | Array
    public object? GlobalUnset { get; set; }
    [JsonProperty("projectConfig", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? ProjectConfig { get; set; }
    [JsonProperty("projectUnset", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | Array
    public object? ProjectUnset { get; set; }
}
