// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ValidateFilesRequest
/// Discriminator: type = "validateFiles"
/// Source: webview-messages.ts
/// </summary>
public class ValidateFilesRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "validateFiles";
    [JsonProperty("id")]
    public string Id { get; set; }
    [JsonProperty("paths")]
    public List<string> Paths { get; set; }
}
