// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs;

/// <summary>
/// Marker interface for WebView request messages (sent from webview to extension).
/// Inherits from IWebviewMessage for unified handling.
/// </summary>
public interface IWebviewMessageRequest : IWebviewMessage
{
}
