// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.ExtensionMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: GitRemoteUrlLoadedMessage
/// Discriminator: type = "gitRemoteUrlLoaded"
/// Source: extension-messages.ts
/// </summary>
public class GitRemoteUrlLoadedMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "gitRemoteUrlLoaded";
    [JsonProperty("gitUrl", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: null | string
    public string? GitUrl { get; set; }
}
