//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Migration;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: defaultModelType
/// Source: migration.ts
/// Signature hash: b6a913052b7b148553fd4d3f433fa866c1268df303467f65ff87772ffd8c2b77
/// </summary>
public partial class DefaultModelType
{
    [JsonProperty("provider")]
    public string Provider { get; set; }
    [JsonProperty("model")]
    public string Model { get; set; }
}
