// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Migration;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.ExtensionMessages;

/// <summary>
/// WebView message: MigrationStateMessage
/// Discriminator: type = "migrationState"
/// Source: migration.ts
/// Signature hash: ceb61c645ddad49fa6e203b0151aa25b4bd62f609fea1615605947954d83be3d
/// </summary>
public class MigrationStateMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "migrationState";
    [JsonProperty("needed")]
    public bool Needed { get; set; }
    [JsonProperty("source")]
    // Original TypeScript type: literal
    public string Source { get; set; }
}
