// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Migration;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.ExtensionMessages;

/// <summary>
/// WebView message: MigrationCompleteMessage
/// Discriminator: type = "migrationComplete"
/// Source: migration.ts
/// Signature hash: ac863ca58c93834f0ae3e15ff8d2a25c5b8a2fd6fdd23e473f5bfb5c1f3dc52f
/// </summary>
public class MigrationCompleteMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "migrationComplete";
    [JsonProperty("source")]
    // Original TypeScript type: MigrationSource
    public MigrationSource Source { get; set; }
    [JsonProperty("operationId")]
    public string OperationId { get; set; }
    [JsonProperty("results")]
    public List<MigrationResultItem> Results { get; set; }
}
