//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Migration;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: MigrationResultItem
/// Source: migration.ts
/// </summary>
public partial class MigrationResultItem
{
    [JsonProperty("item")]
    public string Item { get; set; }
    [JsonProperty("category", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: provider | mcpServer | customMode | session | defaultModel | settings
    public object? Category { get; set; }
    [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: success | error | warning
    public object? Status { get; set; }
    [JsonProperty("message", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Message { get; set; }
}
