//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Migration;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: MigrationProgressMessageSettingsType
/// Source: migration.ts
/// Signature hash: 673cb6fd978226d985e3b84b4d544fd59d723b40edb07b5882ab5314cc4d60a5
/// </summary>
public partial class MigrationProgressMessageSettingsType : IWebviewMessage
{
    [JsonProperty("autoApproval")]
    // Original TypeScript type: MigrationAutoApprovalSelections
    public MigrationAutoApprovalSelections AutoApproval { get; set; }
    [JsonProperty("language")]
    public bool Language { get; set; }
    [JsonProperty("autocomplete")]
    public bool Autocomplete { get; set; }
}
