// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Migration;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: MigrationDataMessage
/// Discriminator: type = "migrationData"
/// Source: migration.ts
/// </summary>
public class MigrationDataMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "migrationData";
    [JsonProperty("source")]
    // Original TypeScript type: MigrationSource
    public MigrationSource Source { get; set; }
    [JsonProperty("operationId")]
    public string OperationId { get; set; }
    [JsonProperty("data")]
    // Original TypeScript type: dataType
    public DataType Data { get; set; }
}
