// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Migration;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: StartMigrationMessage
/// Discriminator: type = "startMigration"
/// Source: migration.ts
/// Signature hash: af500dd928be034768c2a7cdf6aa3eb8f09a054aef31cf7c777c43cb07a4b8ba
/// </summary>
public partial class StartMigrationMessage : IWebviewMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "startMigration";
    [JsonProperty("source")]
    // Original TypeScript type: MigrationSource
    public MigrationSourceEnum Source { get; set; }
    [JsonProperty("operationId")]
    public string OperationId { get; set; }
    [JsonProperty("selections")]
    // Original TypeScript type: StartMigrationMessageSelectionsType
    public StartMigrationMessageSelectionsType Selections { get; set; }
}
