//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Agents;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: AgentConfig
/// Source: agents.ts
/// </summary>
public partial class AgentConfig : IWebviewMessage
{
    [JsonProperty("model", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | null | string
    public string? Model { get; set; }
    [JsonProperty("variant", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | null | string
    public string? Variant { get; set; }
    [JsonProperty("prompt", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | null | string
    public string? Prompt { get; set; }
    [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | null | string
    public string? Description { get; set; }
    [JsonProperty("mode", NullValueHandling = NullValueHandling.Ignore)]
    public PrimarySubagentAllEnum? Mode { get; set; }
    [JsonProperty("hidden", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public bool? Hidden { get; set; }
    [JsonProperty("disable", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public bool? Disable { get; set; }
    [JsonProperty("temperature", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | null | number
    public double? Temperature { get; set; }
    [JsonProperty("top_p", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | null | number
    public double? Top_p { get; set; }
    [JsonProperty("steps", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | null | number
    public double? Steps { get; set; }
    [JsonProperty("requirements", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | AgentRequirements
    public AgentRequirements? Requirements { get; set; }
    [JsonProperty("permission", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Permission { get; set; }
}
