//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.KiloConfig;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: FeatureFlags
/// Source: config.ts
/// </summary>
public class FeatureFlags
{
    [JsonProperty("indexing")]
    public bool Indexing { get; set; }
    [JsonProperty("sandboxControls")]
    public bool SandboxControls { get; set; }
}
