// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.migration;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: LegacyAutocompleteSettings
/// Source: migration.ts
/// </summary>
public class LegacyAutocompleteSettings
{
    [JsonProperty("enableAutoTrigger", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public bool? EnableAutoTrigger { get; set; }
    [JsonProperty("enableSmartInlineTaskKeybinding", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public bool? EnableSmartInlineTaskKeybinding { get; set; }
    [JsonProperty("enableChatAutocomplete", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public bool? EnableChatAutocomplete { get; set; }
}
