// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.Migration;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: MigrationStateMessage
/// Discriminator: type = "migrationState"
/// Source: migration.ts
/// </summary>
public class MigrationStateMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "migrationState";
    [JsonProperty("needed")]
    public bool Needed { get; set; }
    [JsonProperty("source")]
    // Original TypeScript type: literal
    public string Source { get; set; }
}
