//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.migration;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: MigrationSessionSelection
/// Source: migration.ts
/// </summary>
public class MigrationSessionSelection
{
    [JsonProperty("id")]
    public string Id { get; set; }
    [JsonProperty("force", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public bool? Force { get; set; }
}
