// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

/// <summary>
/// Enum: EnvConfigCustomApiEnum
/// Generated from inline string literal union
/// Members: api, config, custom, env
/// Used by: Provider
/// </summary>
[JsonConverter(typeof(StringEnumConverter))]
public enum EnvConfigCustomApiEnum
{
    [JsonProperty("api")]
    Api,
    [JsonProperty("config")]
    Config,
    [JsonProperty("custom")]
    Custom,
    [JsonProperty("env")]
    Env
}
