// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

/// <summary>
/// Enum: LocalRemote
/// Generated from union type
/// </summary>
[JsonConverter(typeof(StringEnumConverter))]
public enum LocalRemote
{
    [JsonProperty("local")]
    Local,
    [JsonProperty("remote")]
    Remote
}
