// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

/// <summary>
/// Enum: ReplacePrependReconcileEnum
/// Generated from inline string literal union
/// Members: prepend, reconcile, replace
/// Used by: MessagesLoadedMessage
/// </summary>
[JsonConverter(typeof(StringEnumConverter))]
public enum ReplacePrependReconcileEnum
{
    [JsonProperty("prepend")]
    Prepend,
    [JsonProperty("reconcile")]
    Reconcile,
    [JsonProperty("replace")]
    Replace
}
