//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: ReviewCommentData
/// Source: ..\..\..\..\src\shared\review-comments.ts
/// </summary>
public class ReviewCommentData
{
    [JsonProperty("id")]
    public string Id { get; set; }
    [JsonProperty("file")]
    public string File { get; set; }
    [JsonProperty("side")]
    // Original TypeScript type: literal
    public string Side { get; set; }
    [JsonProperty("line")]
    public double Line { get; set; }
    [JsonProperty("comment")]
    public string Comment { get; set; }
    [JsonProperty("selectedText")]
    public string SelectedText { get; set; }
}
