//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Parts;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: FileAttachment
/// Source: parts.ts
/// </summary>
public class FileAttachment
{
    [JsonProperty("mime")]
    public string Mime { get; set; }
    [JsonProperty("url")]
    public string Url { get; set; }
    [JsonProperty("filename", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Filename { get; set; }
    [JsonProperty("source", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | FilePartSource
    public FilePartSource? Source { get; set; }
}
