//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Questions;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: toolType
/// Source: questions.ts
/// </summary>
public class ToolType
{
    [JsonProperty("messageID")]
    public string MessageID { get; set; }
    [JsonProperty("callID")]
    public string CallID { get; set; }
}
