// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

/// <summary>
/// Enum: GhmissingGhauthFetchfailedEnum
/// Generated from inline string literal union
/// Members: fetch_failed, gh_auth, gh_missing
/// Used by: AgentManagerPRStatusMessage
/// </summary>
[JsonConverter(typeof(StringEnumConverter))]
public enum GhmissingGhauthFetchfailedEnum
{
    [JsonProperty("fetch_failed")]
    Fetch_failed,
    [JsonProperty("gh_auth")]
    Gh_auth,
    [JsonProperty("gh_missing")]
    Gh_missing
}
