// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

/// <summary>
/// Enum: UnifiedSplitEnum
/// Generated from inline string literal union
/// Members: split, unified
/// Used by: AgentManagerStateMessage
/// </summary>
[JsonConverter(typeof(StringEnumConverter))]
public enum UnifiedSplitEnum
{
    [JsonProperty("split")]
    Split,
    [JsonProperty("unified")]
    Unified
}
