// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.Connection;

/// <summary>
/// Enum: SessionStatusInfo
/// Generated from union type
/// Source: connection.ts
/// </summary>
public enum SessionStatusInfo
{

}
