// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: AgentManagerOpenSessionsMessage
/// Discriminator: type = "agentManager.openSessions"
/// Source: webview-messages.ts
/// Signature hash: 4c918a6cd4dfaf96a92c4ab43155bee0f6e9b99b095f02b6e58449bfa3609cbe
/// </summary>
public partial class AgentManagerOpenSessionsMessage : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.openSessions";
    [JsonProperty("sessionIDs")]
    public List<string> SessionIDs { get; set; }
}
