// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: AgentManagerTerminalCloseRequest
/// Discriminator: type = "agentManager.terminal.close"
/// Source: webview-messages.ts
/// Signature hash: e25f86523e5137b1507da9d3a87bc1c21deced52a4ac0927ff6e95756067de78
/// </summary>
public partial class AgentManagerTerminalCloseRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.terminal.close";
    [JsonProperty("terminalId")]
    public string TerminalId { get; set; }
}
