// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs;

/// <summary>
/// WebView message: ApplyWorkStyleMessage
/// Discriminator: type = "applyWorkStyle"
/// Source: webview-messages.ts
/// Signature hash: e568f947485cfe582b14ab244acf175c955b62e975d7f842d3e56c8a6205d0ec
/// </summary>
public partial class ApplyWorkStyleMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "applyWorkStyle";
    [JsonProperty("style")]
    // Original TypeScript type: WorkStyle
    public WorkStyleEnum Style { get; set; }
}
