// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ClearSessionRequest
/// Discriminator: type = "clearSession"
/// Source: webview-messages.ts
/// Signature hash: 4fe0aa1265f0d6b51679f6dc07c93f90af47638f3dd34d9b2019fcff46390b54
/// </summary>
public partial class ClearSessionRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "clearSession";
}
