// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ContinueInWorktreeRequest
/// Discriminator: type = "continueInWorktree"
/// Source: webview-messages.ts
/// Signature hash: 524c61da7228e6e13fddb3d5d8d2f0ef44df9c19acdaa2cc6be611510ba5fa3e
/// </summary>
public partial class ContinueInWorktreeRequest : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "continueInWorktree";
    [JsonProperty("sessionId")]
    public string SessionId { get; set; }
}
