// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: CreateSectionRequest
/// Discriminator: type = "agentManager.createSection"
/// Source: webview-messages.ts
/// Signature hash: 79a3d803617230a2dab85feb92d8848efc40e4e3f700ef28567309af6f2d8b0a
/// </summary>
public partial class CreateSectionRequest : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.createSection";
    [JsonProperty("name")]
    public string Name { get; set; }
    [JsonProperty("color", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Color { get; set; }
    [JsonProperty("worktreeIds", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | Array
    public object? WorktreeIds { get; set; }
}
