// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: DiffViewerSetBaseBranchRequest
/// Discriminator: type = "diffViewer.setBaseBranch"
/// Source: webview-messages.ts
/// Signature hash: 490b236d433f6d187efeeb3b6755fa007d4b463fc5a21cc29cef2930ec6de9df
/// </summary>
public class DiffViewerSetBaseBranchRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "diffViewer.setBaseBranch";
    [JsonProperty("branch", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Branch { get; set; }
}
