// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: DiffViewerSetDiffStyleRequest
/// Discriminator: type = "diffViewer.setDiffStyle"
/// Source: webview-messages.ts
/// Signature hash: 5b935e08a0446ec60d88c277cbdd01753e79c26884d21a23e8c5419a86a63d16
/// </summary>
public partial class DiffViewerSetDiffStyleRequest : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "diffViewer.setDiffStyle";
    [JsonProperty("style", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: unified | split
    public object? Style { get; set; }
}
