// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs;

/// <summary>
/// WebView message: DiffViewerSendCommentsRequest
/// Discriminator: type = "diffViewer.sendComments"
/// Source: webview-messages.ts
/// Signature hash: 9d8862cc7a038ecbb589264b3816d1ac6fcbdd9b6948ae8d1177b042a3fdbb4d
/// </summary>
public partial class DiffViewerSendCommentsRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "diffViewer.sendComments";
    [JsonProperty("comments")]
    public List<ReviewCommentData> Comments { get; set; }
    [JsonProperty("autoSend")]
    public bool AutoSend { get; set; }
}
