// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: FetchMarketplaceDataMessage
/// Discriminator: type = "fetchMarketplaceData"
/// Source: webview-messages.ts
/// Signature hash: f7a7048bdb653c60a228b3bde65a5e25ec83285d767e1c0323e122afe63ab2ad
/// </summary>
public partial class FetchMarketplaceDataMessage : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "fetchMarketplaceData";
}
