// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs;

/// <summary>
/// WebView message: FilterMarketplaceItemsMessage
/// Discriminator: type = "filterMarketplaceItems"
/// Source: webview-messages.ts
/// Signature hash: 6863172226cdec4dda494de5723081529602c72d13fdf8baebe9fc4d112ecc37
/// </summary>
public partial class FilterMarketplaceItemsMessage : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "filterMarketplaceItems";
    [JsonProperty("filters")]
    // Original TypeScript type: MarketplaceFilters
    public MarketplaceFilters Filters { get; set; }
}
