// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ForkSessionRequest
/// Discriminator: type = "agentManager.forkSession"
/// Source: webview-messages.ts
/// Signature hash: bee2a16ac8a0e3fd5e40ac272177e07feb3fcc08dfd2cdc1ae9240f7224c164d
/// </summary>
public partial class ForkSessionRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.forkSession";
    [JsonProperty("sessionId")]
    public string SessionId { get; set; }
    [JsonProperty("worktreeId", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? WorktreeId { get; set; }
    [JsonProperty("messageId", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? MessageId { get; set; }
}
