// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ImportFromPRRequest
/// Discriminator: type = "agentManager.importFromPR"
/// Source: webview-messages.ts
/// Signature hash: 4b8972657d4defb69d9c7dd9e13c2b33761bf3f267578e59bb1a5c403f16440a
/// </summary>
public partial class ImportFromPRRequest : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.importFromPR";
    [JsonProperty("url")]
    public string Url { get; set; }
}
