//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: labelsType
/// Source: webview-messages.ts
/// </summary>
public class LabelsType
{
    [JsonProperty("scope")]
    public string Scope { get; set; }
    [JsonProperty("statusLoaded")]
    public string StatusLoaded { get; set; }
    [JsonProperty("statusLoadedLegacy")]
    public string StatusLoadedLegacy { get; set; }
    [JsonProperty("statusNotLoaded")]
    public string StatusNotLoaded { get; set; }
    [JsonProperty("statusCreate")]
    public string StatusCreate { get; set; }
    [JsonProperty("title")]
    public string Title { get; set; }
    [JsonProperty("placeholder")]
    public string Placeholder { get; set; }
    [JsonProperty("noWorkspace")]
    public string NoWorkspace { get; set; }
    [JsonProperty("openFailed")]
    public string OpenFailed { get; set; }
    [JsonProperty("sourceXdg")]
    public string SourceXdg { get; set; }
    [JsonProperty("sourceHomeKilo")]
    public string SourceHomeKilo { get; set; }
    [JsonProperty("sourceHomeKilocode")]
    public string SourceHomeKilocode { get; set; }
    [JsonProperty("sourceHomeOpencode")]
    public string SourceHomeOpencode { get; set; }
    [JsonProperty("sourceEnvFile")]
    public string SourceEnvFile { get; set; }
    [JsonProperty("sourceEnvDir")]
    public string SourceEnvDir { get; set; }
    [JsonProperty("sourceEnvContent")]
    public string SourceEnvContent { get; set; }
    [JsonProperty("sourceProjectKilo")]
    public string SourceProjectKilo { get; set; }
    [JsonProperty("sourceProjectRoot")]
    public string SourceProjectRoot { get; set; }
    [JsonProperty("sourceProjectKilocode")]
    public string SourceProjectKilocode { get; set; }
    [JsonProperty("sourceProjectOpencode")]
    public string SourceProjectOpencode { get; set; }
}
