// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: OpenSettingsPanelRequest
/// Discriminator: type = "openSettingsPanel"
/// Source: webview-messages.ts
/// Signature hash: 1f31d0e3c9d35006729a4b2a28e598378cb5f3b3cbcfa6b831ef200724b275f0
/// </summary>
public partial class OpenSettingsPanelRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "openSettingsPanel";
    [JsonProperty("tab", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Tab { get; set; }
}
