// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: OpenSubAgentViewerRequest
/// Discriminator: type = "openSubAgentViewer"
/// Source: webview-messages.ts
/// Signature hash: 582f501519ca187736271e86c4c71f671e3767b180f2cbeca06f6ff782b44412
/// </summary>
public partial class OpenSubAgentViewerRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "openSubAgentViewer";
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
    [JsonProperty("title", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Title { get; set; }
}
