// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: OpenMarketplacePanelRequest
/// Discriminator: type = "openMarketplacePanel"
/// Source: webview-messages.ts
/// Signature hash: f9f335141e04a52732d0ed661c7818d45aa760edaf52bdb4ca58980b3ee07347
/// </summary>
public partial class OpenMarketplacePanelRequest : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "openMarketplacePanel";
    [JsonProperty("directory", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Directory { get; set; }
}
