// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: OpenWorktreeRequest
/// Discriminator: type = "agentManager.openWorktree"
/// Source: webview-messages.ts
/// Signature hash: d453c93d64f793cadb6c92e708377b76a4eae1d543878d767c20d5f847555bb6
/// </summary>
public partial class OpenWorktreeRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.openWorktree";
    [JsonProperty("worktreeId")]
    public string WorktreeId { get; set; }
}
