// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: OpenVSCodeSettingsRequest
/// Discriminator: type = "openVSCodeSettings"
/// Source: webview-messages.ts
/// Signature hash: 8f4bca3858309affdc819fa743f0d7c930bd09b4cb014ee0e8c4313a7520a15e
/// </summary>
public class OpenVSCodeSettingsRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "openVSCodeSettings";
    [JsonProperty("query")]
    public string Query { get; set; }
}
