// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: OpenFileRequest
/// Discriminator: type = "openFile"
/// Source: webview-messages.ts
/// Signature hash: 3c922c54d108e3ba29c478769ebc3d40245e10f476f072b8492272c3f1350737
/// </summary>
public partial class OpenFileRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "openFile";
    [JsonProperty("filePath")]
    public string FilePath { get; set; }
    [JsonProperty("line", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? Line { get; set; }
    [JsonProperty("column", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? Column { get; set; }
}
