// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: PermissionResponseRequest
/// Discriminator: type = "permissionResponse"
/// Source: webview-messages.ts
/// Signature hash: cc06e53d03d62330b4be777ac0a8545aabb71ee65e82cb44ab6db850e1635fbe
/// </summary>
public partial class PermissionResponseRequest : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "permissionResponse";
    [JsonProperty("permissionId")]
    public string PermissionId { get; set; }
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
    [JsonProperty("response", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: once | always | reject
    public object? Response { get; set; }
    [JsonProperty("approvedAlways")]
    public List<string> ApprovedAlways { get; set; }
    [JsonProperty("deniedAlways")]
    public List<string> DeniedAlways { get; set; }
}
