// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: PersistSessionRequest
/// Discriminator: type = "agentManager.persistSession"
/// Source: webview-messages.ts
/// Signature hash: 83f3c78015a9c30759500ab5f9a56f5d5f3de079a36d505d407a2f6230361775
/// </summary>
public partial class PersistSessionRequest : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.persistSession";
    [JsonProperty("sessionId")]
    public string SessionId { get; set; }
    [JsonProperty("draftID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? DraftID { get; set; }
}
