// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: RemoveStaleWorktreeRequest
/// Discriminator: type = "agentManager.removeStaleWorktree"
/// Source: webview-messages.ts
/// Signature hash: 52bfaf5bb1b6d08f582b942560ba471517add96c5853a0651b1bb003220780d4
/// </summary>
public partial class RemoveStaleWorktreeRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.removeStaleWorktree";
    [JsonProperty("worktreeId")]
    public string WorktreeId { get; set; }
}
