// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.Types;
using KiloExtensionDTOs;

/// <summary>
/// WebView message: RemoveInstalledMarketplaceItemMessage
/// Discriminator: type = "removeInstalledMarketplaceItem"
/// Source: webview-messages.ts
/// Signature hash: 24d1e4ce29e16f304c2eaca63aaa831f9df4dcd8b795de5187bd0aa0ef813267
/// </summary>
public partial class RemoveInstalledMarketplaceItemMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "removeInstalledMarketplaceItem";
    [JsonProperty("mpItem")]
    // Original TypeScript type: MarketplaceItem
    public object MpItem { get; set; }
    [JsonProperty("mpInstallOptions")]
    // Original TypeScript type: InstallMarketplaceItemOptions
    public InstallMarketplaceItemOptions MpInstallOptions { get; set; }
}
