// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: RequestChatSettingsMessage
/// Discriminator: type = "requestChatSettings"
/// Source: webview-messages.ts
/// Signature hash: 16657c34b8c9ada2c9f26b0c23cd1b15611abac49d76e6700445646741248089
/// </summary>
public class RequestChatSettingsMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "requestChatSettings";
}
