// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: RequestSandboxDefaultMessage
/// Discriminator: type = "requestSandboxDefault"
/// Source: webview-messages.ts
/// Signature hash: 5f93e2e5b89e989c4d90d611f607921a3ae1ed203ebf64607f52d9466be259b9
/// </summary>
public partial class RequestSandboxDefaultMessage : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "requestSandboxDefault";
    [JsonProperty("requestID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? RequestID { get; set; }
    [JsonProperty("agentManagerContext", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? AgentManagerContext { get; set; }
    [JsonProperty("contextDirectory", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? ContextDirectory { get; set; }
}
