// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: RequestProvidersMessage
/// Discriminator: type = "requestProviders"
/// Source: webview-messages.ts
/// Signature hash: 49133198d6121dbd996d06f2ec5c6743b273b1a99262ac88a9f16d615c6beb00
/// </summary>
public partial class RequestProvidersMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "requestProviders";
}
