// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: RequestGitChangesContextMessage
/// Discriminator: type = "requestGitChangesContext"
/// Source: webview-messages.ts
/// Signature hash: 283160ecf371b3591b438ec4923147fc7ee258445a7cb012ac9a05379bc98e45
/// </summary>
public partial class RequestGitChangesContextMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "requestGitChangesContext";
    [JsonProperty("requestId")]
    public string RequestId { get; set; }
    [JsonProperty("sessionID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? SessionID { get; set; }
    [JsonProperty("agentManagerContext", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? AgentManagerContext { get; set; }
}
