// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: RequestTimelineSettingMessage
/// Discriminator: type = "requestTimelineSetting"
/// Source: webview-messages.ts
/// Signature hash: d2267cf868b92da9b354ebc1c5d7b95e20686a51a6a720fcc2aef78b9cf5156c
/// </summary>
public partial class RequestTimelineSettingMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "requestTimelineSetting";
}
