// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: RequestNotificationSettingsMessage
/// Discriminator: type = "requestNotificationSettings"
/// Source: webview-messages.ts
/// Signature hash: 3e3f6e131ab97bf6b977dbca12ed8c609f839f04932c932e3499cdb44ff29783
/// </summary>
public class RequestNotificationSettingsMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "requestNotificationSettings";
}
