// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: RequestWorkStyleMessage
/// Discriminator: type = "requestWorkStyle"
/// Source: webview-messages.ts
/// Signature hash: 9fae581649779a3b183c8cb2bab4969cdd722eb72df1aaf85dbd6bff9b93f0cd
/// </summary>
public class RequestWorkStyleMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "requestWorkStyle";
}
