// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: RequestFavoritesMessage
/// Discriminator: type = "requestFavorites"
/// Source: webview-messages.ts
/// Signature hash: 3ab0223b02430a24ccb7b7e489b3a542775f09925b8e5cf4310e6db78c72e4e7
/// </summary>
public partial class RequestFavoritesMessage : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "requestFavorites";
}
