// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: RequestWorktreeDiffFileMessage
/// Discriminator: type = "agentManager.requestWorktreeDiffFile"
/// Source: webview-messages.ts
/// Signature hash: b3f78f0caaa6c59086f33cb6de9e21bddc285de2191bedd1beac9633864d1dab
/// </summary>
public partial class RequestWorktreeDiffFileMessage : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.requestWorktreeDiffFile";
    [JsonProperty("sessionId")]
    public string SessionId { get; set; }
    [JsonProperty("file")]
    public string File { get; set; }
}
