// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: RequestStateMessage
/// Discriminator: type = "agentManager.requestState"
/// Source: webview-messages.ts
/// Signature hash: df2d3669d20a0087e93d7464a25e1127f6b06840d7d5513aea5d9e6d8ad62aa2
/// </summary>
public partial class RequestStateMessage : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.requestState";
}
