// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: RequestConfigMessage
/// Discriminator: type = "requestConfig"
/// Source: webview-messages.ts
/// Signature hash: 99e124431e07d3ceaaf888a17ebf263ffec1222495793dd8f70569b86151724c
/// </summary>
public partial class RequestConfigMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "requestConfig";
}
