// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: RequestModelSelectorExpandedMessage
/// Discriminator: type = "requestModelSelectorExpanded"
/// Source: webview-messages.ts
/// Signature hash: 043a234cdcb8fb909d4e32124af28b13ae541078f32ceb9d9f1280afb4b342d5
/// </summary>
public class RequestModelSelectorExpandedMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "requestModelSelectorExpanded";
}
