// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: RequestCommandsMessage
/// Discriminator: type = "requestCommands"
/// Source: webview-messages.ts
/// Signature hash: 7dace3effd0a41f4bca59d5682f9544ed7cb453fd62633487e75879861f2eec4
/// </summary>
public partial class RequestCommandsMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "requestCommands";
}
