// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: RequestSandboxStatusMessage
/// Discriminator: type = "requestSandboxStatus"
/// Source: webview-messages.ts
/// Signature hash: 731e57cc63338a5f8f922ccb252afe349d657c421033804c46ecf1b8d8081515
/// </summary>
public partial class RequestSandboxStatusMessage : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "requestSandboxStatus";
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
}
