// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: RequestRecentsMessage
/// Discriminator: type = "requestRecents"
/// Source: webview-messages.ts
/// Signature hash: 97ab17bc49999190dee97c9d4dde65e4e6803962d8e73aa29759eb6dad4efb78
/// </summary>
public class RequestRecentsMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "requestRecents";
}
