// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ResetAllSettingsRequest
/// Discriminator: type = "resetAllSettings"
/// Source: webview-messages.ts
/// Signature hash: 88330352f18e030dbadb6812b84b037cb5b89c5907248ae37b4c430fb9f95d21
/// </summary>
public class ResetAllSettingsRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "resetAllSettings";
}
