// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: RevertWorktreeFileMessage
/// Discriminator: type = "agentManager.revertWorktreeFile"
/// Source: webview-messages.ts
/// Signature hash: 73687280b781b8d0142c6529892b7d2205a034de7e8e77f76c88c8b9df14e026
/// </summary>
public partial class RevertWorktreeFileMessage : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.revertWorktreeFile";
    [JsonProperty("sessionId")]
    public string SessionId { get; set; }
    [JsonProperty("file")]
    public string File { get; set; }
}
