// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: RevertSessionRequest
/// Discriminator: type = "revertSession"
/// Source: webview-messages.ts
/// Signature hash: 082407fede623d0c99e0f25d439908825d4a0c79e8420f89e4bc3c9a18757446
/// </summary>
public partial class RevertSessionRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "revertSession";
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
    [JsonProperty("messageID")]
    public string MessageID { get; set; }
    [JsonProperty("partID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? PartID { get; set; }
}
