// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.Providers;

/// <summary>
/// WebView message: SaveCustomProviderMessage
/// Discriminator: type = "saveCustomProvider"
/// Source: webview-messages.ts
/// Signature hash: ed8262a23caef9819919481a9d6b89a0ec2bd3aebcf574beff76d987c881e064
/// </summary>
public partial class SaveCustomProviderMessage : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "saveCustomProvider";
    [JsonProperty("requestId")]
    public string RequestId { get; set; }
    [JsonProperty("providerID")]
    public string ProviderID { get; set; }
    [JsonProperty("config")]
    // Original TypeScript type: ProviderConfig
    public ProviderConfig Config { get; set; }
    [JsonProperty("apiKey", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? ApiKey { get; set; }
    [JsonProperty("apiKeyChanged", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public bool? ApiKeyChanged { get; set; }
}
