// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SaveImageRequest
/// Discriminator: type = "saveImage"
/// Source: webview-messages.ts
/// Signature hash: a4d39a72f1395eaa7738c8d0b25cb1ca4d0430c1fd72ba538236f7a294adbf3e
/// </summary>
public partial class SaveImageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "saveImage";
    [JsonProperty("dataUrl")]
    public string DataUrl { get; set; }
    [JsonProperty("filename")]
    public string Filename { get; set; }
}
