// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SelectSourceRequest
/// Discriminator: type = "selectSource"
/// Source: webview-messages.ts
/// Signature hash: f0837bb70cf9e2cb2b6b1524c86557a9057ade088fc888b41c0e967db9934bd4
/// </summary>
public partial class SelectSourceRequest : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "selectSource";
    [JsonProperty("id")]
    public string Id { get; set; }
}
