// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SendCommandRequest
/// Discriminator: type = "sendCommand"
/// Source: webview-messages.ts
/// Signature hash: 4e1a6819f37414dd6d18bd90c5d76d5ec0c3a79bf98ef1cb46d2db4f6144a204
/// </summary>
public partial class SendCommandRequest : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "sendCommand";
    [JsonProperty("command")]
    public string Command { get; set; }
    [JsonProperty("arguments")]
    public string Arguments { get; set; }
    [JsonProperty("messageID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? MessageID { get; set; }
    [JsonProperty("sessionID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? SessionID { get; set; }
    [JsonProperty("draftID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? DraftID { get; set; }
    [JsonProperty("providerID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? ProviderID { get; set; }
    [JsonProperty("modelID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? ModelID { get; set; }
    [JsonProperty("agent", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Agent { get; set; }
    [JsonProperty("variant", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Variant { get; set; }
    [JsonProperty("files", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | Array
    public object? Files { get; set; }
    [JsonProperty("agentManagerContext", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? AgentManagerContext { get; set; }
    [JsonProperty("contextDirectory", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? ContextDirectory { get; set; }
}
