// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SetReviewMarkdownRenderRequest
/// Discriminator: type = "agentManager.setReviewMarkdownRender"
/// Source: webview-messages.ts
/// Signature hash: 694d47e8c66c8fc8d08b9a8ad28654afb4cad624cac05f9fb4ca5a7575475aaf
/// </summary>
public class SetReviewMarkdownRenderRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.setReviewMarkdownRender";
    [JsonProperty("render")]
    public bool Render { get; set; }
}
