// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SetSandboxDefaultMessage
/// Discriminator: type = "setSandboxDefault"
/// Source: webview-messages.ts
/// Signature hash: cc4fe1cdd44dc81e3ded0bdcf678f477b9d65e0d9a5e9aab9fbe8168095232ab
/// </summary>
public partial class SetSandboxDefaultMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "setSandboxDefault";
    [JsonProperty("enabled")]
    public bool Enabled { get; set; }
    [JsonProperty("requestID")]
    public string RequestID { get; set; }
    [JsonProperty("agentManagerContext", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? AgentManagerContext { get; set; }
    [JsonProperty("contextDirectory", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? ContextDirectory { get; set; }
}
