// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SetSessionsCollapsedRequest
/// Discriminator: type = "agentManager.setSessionsCollapsed"
/// Source: webview-messages.ts
/// Signature hash: 2003ab25c0b0d15fe6306bf1fc1049e4c553773c0ca4f25f7cccdd977dd8bbf1
/// </summary>
public partial class SetSessionsCollapsedRequest : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.setSessionsCollapsed";
    [JsonProperty("collapsed")]
    public bool Collapsed { get; set; }
}
