// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SetTabOrderRequest
/// Discriminator: type = "agentManager.setTabOrder"
/// Source: webview-messages.ts
/// Signature hash: a95179260d09aaee6ce2528ac854039237ab13cf754db1c1fc10e41adee649bb
/// </summary>
public partial class SetTabOrderRequest : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.setTabOrder";
    [JsonProperty("key")]
    public string Key { get; set; }
    [JsonProperty("order")]
    public List<string> Order { get; set; }
}
