// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ShowLocalTerminalRequest
/// Discriminator: type = "agentManager.showLocalTerminal"
/// Source: webview-messages.ts
/// Signature hash: d974df9e4cb6c4a6c352bc28286812dcfb5dd5a07ea0d3054694fd9e3f0f2487
/// </summary>
public partial class ShowLocalTerminalRequest : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.showLocalTerminal";
}
