// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SidebarOpenSessionsMessage
/// Discriminator: type = "sidebar.openSessions"
/// Source: webview-messages.ts
/// Signature hash: 8a12cb8b07d8cb665ade9d75cc96717026051e677a0cb1b6a5c0e21f3d90082f
/// </summary>
public class SidebarOpenSessionsMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "sidebar.openSessions";
    [JsonProperty("sessionIDs")]
    public List<string> SessionIDs { get; set; }
}
