// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: StartDiffWatchMessage
/// Discriminator: type = "agentManager.startDiffWatch"
/// Source: webview-messages.ts
/// Signature hash: d87941c68b14b202252c0182d70fc83c5d89726b952d33ca47472b41d3a1ad6b
/// </summary>
public partial class StartDiffWatchMessage : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.startDiffWatch";
    [JsonProperty("sessionId")]
    public string SessionId { get; set; }
}
