// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: StopRunScriptRequest
/// Discriminator: type = "agentManager.stopRunScript"
/// Source: webview-messages.ts
/// Signature hash: 43f69e8fde98d8fc051665e5d85fe2c9db3367533ec2a6beae9cf97d52485133
/// </summary>
public partial class StopRunScriptRequest : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.stopRunScript";
    [JsonProperty("worktreeId")]
    public string WorktreeId { get; set; }
}
