// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: StreamSessionVisibleMessage
/// Discriminator: type = "streamSessionVisible"
/// Source: webview-messages.ts
/// Signature hash: cc3a18f6099879a9f65ebf33f05a4ee950dfdfe305f59023bac7d55075f5b7ab
/// </summary>
public class StreamSessionVisibleMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "streamSessionVisible";
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
    [JsonProperty("visible")]
    public bool Visible { get; set; }
}
