// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: TestNotificationMessage
/// Discriminator: type = "testNotification"
/// Source: webview-messages.ts
/// Signature hash: eb471ca19c70f228537ed4b0aaf9248ee320c3da3427be01926b07077a968f8b
/// </summary>
public partial class TestNotificationMessage : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "testNotification";
    [JsonProperty("sound")]
    public string Sound { get; set; }
}
