// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: UnrevertSessionRequest
/// Discriminator: type = "unrevertSession"
/// Source: webview-messages.ts
/// Signature hash: a81bfb063f815df13138be050d9a68063dbd26964906d7b55143b80e57780d08
/// </summary>
public partial class UnrevertSessionRequest : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "unrevertSession";
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
}
