// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: UpdateSettingRequest
/// Discriminator: type = "updateSetting"
/// Source: webview-messages.ts
/// Signature hash: 6e7bd814efc30fb38062d9e7c5967ce2fdbb611709c03785a319b576bafaeef6
/// </summary>
public partial class UpdateSettingRequest : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "updateSetting";
    [JsonProperty("key")]
    public string Key { get; set; }
    [JsonProperty("value")]
    public object Value { get; set; }
}
