// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ValidateFilesRequest
/// Discriminator: type = "validateFiles"
/// Source: webview-messages.ts
/// Signature hash: f1568ce4214530320e0ac6407cfdf9186a83039c8550b15a3f42589c039f9445
/// </summary>
public partial class ValidateFilesRequest : IWebviewMessageRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "validateFiles";
    [JsonProperty("id")]
    public string Id { get; set; }
    [JsonProperty("paths")]
    public List<string> Paths { get; set; }
}
