//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Profile;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: KilocodeNotificationAction
/// Source: profile.ts
/// </summary>
public partial class KilocodeNotificationAction
{
    [JsonProperty("actionText")]
    public string ActionText { get; set; }
    [JsonProperty("actionURL")]
    public string ActionURL { get; set; }
}
