//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Profile;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: KiloPassState
/// Source: profile.ts
/// </summary>
public partial class KiloPassState : IWebviewMessage
{
    [JsonProperty("currentPeriodBaseCreditsUsd")]
    public double CurrentPeriodBaseCreditsUsd { get; set; }
    [JsonProperty("currentPeriodUsageUsd")]
    public double CurrentPeriodUsageUsd { get; set; }
    [JsonProperty("currentPeriodBonusCreditsUsd")]
    public double CurrentPeriodBonusCreditsUsd { get; set; }
    [JsonProperty("nextBillingAt", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | null | string
    public string? NextBillingAt { get; set; }
}
