//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Profile;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: ProfileDataProfileType
/// Source: profile.ts
/// Signature hash: 531e196859572f21772133307b283fcf2554b8ccfe4919a50664d919d1940b2a
/// </summary>
public partial class ProfileDataProfileType
{
    [JsonProperty("email")]
    public string Email { get; set; }
    [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Name { get; set; }
    [JsonProperty("organizations", NullValueHandling = NullValueHandling.Ignore)]
    public List<OrganizationsItemType>? Organizations { get; set; }
    [JsonProperty("selectedOrganizationId", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? SelectedOrganizationId { get; set; }
    [JsonProperty("hasPersonalAccount", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public bool? HasPersonalAccount { get; set; }
}
