//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.Permissions;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloVisualStudioExtension.WebView.Generated;

/// <summary>
/// Type: PermissionRuleItem
/// Source: permissions.ts
/// </summary>
public class PermissionRuleItem
{
    [JsonProperty("permission")]
    public string Permission { get; set; }
    [JsonProperty("pattern")]
    public string Pattern { get; set; }
    [JsonProperty("action")]
    // Original TypeScript type: PermissionLevel
    public PermissionLevel Action { get; set; }
}
