#!/usr/bin/env bun
import * as fs from "fs"
import * as path from "path"

// Contract is 2 levels up (from tools/webview-contract-extractor to packages/kilo-visualstudio)
const VS_DIR = path.resolve(__dirname, "..", "..")
const CONTRACT_PATH = path.join(VS_DIR, "porting/contract/WebViewContract.json")
const OUTPUT_PATH = path.join(VS_DIR, "KiloVisualStudioExtension/WebView/Generated")

interface PropertyDefinition {
  name: string
  type: string
  optional: boolean
  nullable: boolean
  elementType?: string | null
  literalValue?: string | number | boolean | null
  isLiteral: boolean
}

interface DiscriminatorInfo {
  field: string
  value: string
}

interface MessageType {
  name: string
  type: string
  discriminator: DiscriminatorInfo
  properties: PropertyDefinition[]
  sourceFile: string
}

interface WebViewContract {
  schemaVersion: string
  messages: {
    webviewToExtension: MessageType[]
    extensionToWebview: MessageType[]
  }
  types: any[]
}

function pascalCase(name: string): string {
  if (!name) return name
  return name.charAt(0).toUpperCase() + name.slice(1)
}

function mapTypeToCSharp(prop: PropertyDefinition): string {
  const baseType = prop.type.toLowerCase()
  
  if (baseType === "string") return "string"
  if (baseType === "number" || baseType === "integer") return "double"
  if (baseType === "boolean") return "bool"
  if (baseType === "array") return "List<object>"
  if (baseType === "record") return "Dictionary<string, object>"
  if (baseType === "literal") return "string"
  if (baseType === "union") return "object"
  if (baseType === "any" || baseType === "unknown") return "object"
  
  // All other types map to object to avoid compilation errors
  // These would need to be generated as separate classes or referenced from existing code
  return "object"
}

function generateMessageClass(message: MessageType, ns: string): string {
  const sb: string[] = []
  
  sb.push("// <auto-generated>")
  sb.push("//     This code was generated by WebViewContractGenerator.")
  sb.push("//     Do not modify this file directly as changes will be lost on regeneration.")
  sb.push("//     Source: WebViewContract.json schema version " + contract.schemaVersion)
  sb.push("// </auto-generated>")
  sb.push("")
  sb.push("#nullable enable")
  sb.push("")
  sb.push("namespace " + ns + ";")
  sb.push("")
  sb.push("using System;")
  sb.push("using System.Collections.Generic;")
  sb.push("using Newtonsoft.Json;")
  sb.push("")
  sb.push("/// <summary>")
  sb.push("/// WebView message: " + message.name)
  sb.push("/// Discriminator: " + message.discriminator.field + " = \"" + message.discriminator.value + "\"")
  sb.push("/// Source: " + message.sourceFile)
  sb.push("/// </summary>")
  sb.push("public class " + message.name)
  sb.push("{")

  for (const prop of message.properties) {
    const propType = mapTypeToCSharp(prop)
    const nullable = prop.optional || prop.nullable ? "?" : ""
    const jsonAttr = prop.name !== message.discriminator.field 
      ? "    [JsonProperty(\"" + prop.name + "\")]\n" 
      : ""
    
    sb.push(jsonAttr + "    public " + propType + nullable + " " + pascalCase(prop.name) + " { get; set; }")
  }

  sb.push("}")
  sb.push("")

  return sb.join("\n")
}

function generateDiscriminatorFactory(
  webviewToExt: MessageType[], 
  extToWebview: MessageType[], 
  ns: string
): string {
  const sb: string[] = []

  sb.push("// <auto-generated>")
  sb.push("//     This code was generated by WebViewContractGenerator.")
  sb.push("//     Do not modify this file directly as changes will be lost on regeneration.")
  sb.push("// </auto-generated>")
  sb.push("")
  sb.push("#nullable enable")
  sb.push("")
  sb.push("namespace " + ns + ";")
  sb.push("")
  sb.push("using System;")
  sb.push("using Newtonsoft.Json;")
  sb.push("using Newtonsoft.Json.Linq;")
  sb.push("")
  sb.push("using KiloVisualStudioExtension.ApiClient.Json;")
  sb.push("")
  sb.push("/// <summary>")
  sb.push("/// Discriminator-based deserialization factory for WebView messages.")
  sb.push("/// Uses explicit discriminator checking instead of JsonConverter inheritance.")
  sb.push("/// Reuses KiloJsonSerializer configuration from PORT-INFRA-003.")
  sb.push("/// </summary>")
  sb.push("public static class WebViewMessageFactory")
  sb.push("{")
  sb.push("    private static readonly JsonSerializer Serializer = KiloJsonSerializer.Create();")
  sb.push("")
  sb.push("    /// <summary>")
  sb.push("    /// Deserialize a WebView message from JSON using discriminator-based routing.")
  sb.push("    /// </summary>")
  sb.push("    public static T Deserialize<T>(JToken token) where T : class")
  sb.push("    {")
  sb.push("        var type = token[\"type\"]?.Value<string>();")
  sb.push("")
  sb.push("        return type switch")
  sb.push("        {")

  // Deduplicate by discriminator value - keep first occurrence
  const seenDiscriminators = new Set<string>()
  const cases: string[] = []
  
  for (const message of webviewToExt) {
    const discValue = message.discriminator.value
    if (!seenDiscriminators.has(discValue)) {
      cases.push("            \"" + discValue + "\" => typeof(T) == typeof(" + message.name + ") ? (T)(object)token.ToObject<" + message.name + ">(Serializer)! : throw new JsonSerializationException(\"Type mismatch\"),")
      seenDiscriminators.add(discValue)
    }
  }

  for (const message of extToWebview) {
    const discValue = message.discriminator.value
    if (!seenDiscriminators.has(discValue)) {
      cases.push("            \"" + discValue + "\" => typeof(T) == typeof(" + message.name + ") ? (T)(object)token.ToObject<" + message.name + ">(Serializer)! : throw new JsonSerializationException(\"Type mismatch\"),")
      seenDiscriminators.add(discValue)
    }
  }
  
  sb.push(cases.join("\n"))

  sb.push("            _ => throw new JsonSerializationException(\"Unknown message type: \" + type)")
  sb.push("        };")
  sb.push("    }")
  sb.push("")
  sb.push("    /// <summary>")
  sb.push("    /// Deserialize a WebView message from JSON string using discriminator-based routing.")
  sb.push("    /// </summary>")
  sb.push("    public static T Deserialize<T>(string json) where T : class")
  sb.push("    {")
  sb.push("        var token = JToken.Parse(json);")
  sb.push("        return Deserialize<T>(token);")
  sb.push("    }")
  sb.push("}")
  sb.push("")

  return sb.join("\n")
}

console.log("WebView DTO Generator (Bun version)")
console.log("===================================")
console.log()

if (!fs.existsSync(CONTRACT_PATH)) {
  console.error(`Error: Contract file not found: ${CONTRACT_PATH}`)
  process.exit(1)
}

console.log(`Reading contract from: ${CONTRACT_PATH}`)
const contractJson = fs.readFileSync(CONTRACT_PATH, "utf-8")
const contract: WebViewContract = JSON.parse(contractJson)

console.log(`Contract version: ${contract.schemaVersion}`)
console.log(`Total types: ${contract.types.length}`)
console.log(`WebView→Extension messages: ${contract.messages.webviewToExtension.length}`)
console.log(`Extension→WebView messages: ${contract.messages.extensionToWebview.length}`)
console.log()

const ns = "KiloVisualStudioExtension.WebView.Generated"
const webviewToExtDir = path.join(OUTPUT_PATH, "Messages", "WebviewToExtension")
const extToWebviewDir = path.join(OUTPUT_PATH, "Messages", "ExtensionToWebview")

fs.mkdirSync(webviewToExtDir, { recursive: true })
fs.mkdirSync(extToWebviewDir, { recursive: true })

console.log("Generating message classes...")

let generatedCount = 0

// Generate all WebView → Extension messages
const webviewToExtLimit = contract.messages.webviewToExtension.length
for (let i = 0; i < webviewToExtLimit; i++) {
  const message = contract.messages.webviewToExtension[i]
  const code = generateMessageClass(message, ns)
  const filePath = path.join(webviewToExtDir, `${message.name}.cs`)
  fs.writeFileSync(filePath, code)
  generatedCount++
  if (i < 10 || i % 20 === 0) {
    console.log(`  Generated: ${message.name}`)
  }
}

// Generate all Extension → WebView messages
const extToWebviewLimit = contract.messages.extensionToWebview.length
for (let i = 0; i < extToWebviewLimit; i++) {
  const message = contract.messages.extensionToWebview[i]
  const code = generateMessageClass(message, ns)
  const filePath = path.join(extToWebviewDir, `${message.name}.cs`)
  fs.writeFileSync(filePath, code)
  generatedCount++
  if (i < 10 || i % 20 === 0) {
    console.log(`  Generated: ${message.name}`)
  }
}

// Generate discriminator factory
console.log()
console.log("Generating discriminator factory...")
const factoryCode = generateDiscriminatorFactory(
  contract.messages.webviewToExtension,
  contract.messages.extensionToWebview,
  ns
)
const factoryPath = path.join(OUTPUT_PATH, "WebViewMessageFactory.cs")
fs.writeFileSync(factoryPath, factoryCode)
generatedCount++

console.log()
console.log("Generation complete!")
console.log(`Output directory: ${OUTPUT_PATH}`)
console.log(`Total files generated: ${generatedCount}`)
console.log()
console.log("Generated artifacts:")
console.log(`  WebView→Extension: ${webviewToExtLimit} message classes`)
console.log(`  Extension→WebView: ${extToWebviewLimit} message classes`)
console.log(`  Discriminator factory: WebViewMessageFactory.cs`)
console.log()
console.log("To generate all messages, modify the limit in generator.ts")
