// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.Parts;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: StepFinishPart
/// Discriminator: type = "step-finish"
/// Source: parts.ts
/// </summary>
public class StepFinishPart : BasePart
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "step-finish";
    [JsonProperty("reason", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Reason { get; set; }
    [JsonProperty("time", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Time { get; set; }
    [JsonProperty("model", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Model { get; set; }
    [JsonProperty("generationID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? GenerationID { get; set; }
    [JsonProperty("vercelID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? VercelID { get; set; }
    [JsonProperty("cost", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? Cost { get; set; }
    [JsonProperty("tokens", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Tokens { get; set; }
    [JsonProperty("metrics", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | StepThroughputMetrics
    public StepThroughputMetrics? Metrics { get; set; }
}
