// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.parts;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: StepThroughputMetrics
/// Source: parts.ts
/// </summary>
public class StepThroughputMetrics
{
    [JsonProperty("prompt", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? Prompt { get; set; }
    [JsonProperty("generation", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? Generation { get; set; }
    [JsonProperty("source")]
    // Original TypeScript type: literal
    public string Source { get; set; }
}
