// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.parts;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: TokenUsage
/// Source: parts.ts
/// </summary>
public class TokenUsage
{
    [JsonProperty("input")]
    public double Input { get; set; }
    [JsonProperty("output")]
    public double Output { get; set; }
    [JsonProperty("reasoning", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? Reasoning { get; set; }
    [JsonProperty("cache", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Cache { get; set; }
}
