// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.Parts;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloVisualStudioExtension.ApiClient;

/// <summary>
/// WebView message: ToolPart
/// Discriminator: type = "tool"
/// Source: parts.ts
/// </summary>
public class ToolPart
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "tool";
    [JsonProperty("tool")]
    public string Tool { get; set; }
    [JsonProperty("state")]
    // Original TypeScript type: ToolState
    public ToolState State { get; set; }
    [JsonProperty("metadata", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Metadata { get; set; }
    [JsonProperty("callID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? CallID { get; set; }
}
