// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: AgentManagerStateMessage
/// Discriminator: type = "agentManager.state"
/// Source: extension-messages.ts
/// </summary>
public class AgentManagerStateMessage
{
    [JsonProperty("type")]
    public string Type { get; set; }
    [JsonProperty("worktrees")]
    public List<WorktreeState> Worktrees { get; set; }
    [JsonProperty("sessions")]
    public List<ManagedSessionState> Sessions { get; set; }
    [JsonProperty("sections", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | Array
    public object? Sections { get; set; }
    [JsonProperty("staleWorktreeIds", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | Array
    public object? StaleWorktreeIds { get; set; }
    [JsonProperty("tabOrder", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? TabOrder { get; set; }
    [JsonProperty("worktreeOrder", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | Array
    public object? WorktreeOrder { get; set; }
    [JsonProperty("sessionsCollapsed", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public object? SessionsCollapsed { get; set; }
    [JsonProperty("sidebarCollapsed", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public object? SidebarCollapsed { get; set; }
    [JsonProperty("reviewDiffStyle", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | "split" | "unified"
    public object? ReviewDiffStyle { get; set; }
    [JsonProperty("reviewMarkdownRender", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public object? ReviewMarkdownRender { get; set; }
    [JsonProperty("isGitRepo", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public object? IsGitRepo { get; set; }
    [JsonProperty("defaultBaseBranch", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? DefaultBaseBranch { get; set; }
    [JsonProperty("runStatuses", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | Array
    public object? RunStatuses { get; set; }
    [JsonProperty("runScriptConfigured", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public object? RunScriptConfigured { get; set; }
    [JsonProperty("runScriptPath", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? RunScriptPath { get; set; }
}
