// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: AgentManagerOpenFileRequest
/// Discriminator: type = "agentManager.openFile"
/// Source: webview-messages.ts
/// </summary>
public class AgentManagerOpenFileRequest
{
    [JsonProperty("type")]
    public string Type { get; set; }
    [JsonProperty("sessionId")]
    public string SessionId { get; set; }
    [JsonProperty("filePath")]
    public string FilePath { get; set; }
    [JsonProperty("line", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? Line { get; set; }
    [JsonProperty("column", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? Column { get; set; }
}
