// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: AgentManagerSessionMetaMessage
/// Discriminator: type = "agentManager.sessionMeta"
/// Source: extension-messages.ts
/// </summary>
public class AgentManagerSessionMetaMessage
{
    [JsonProperty("type")]
    public string Type { get; set; }
    [JsonProperty("sessionId")]
    public string SessionId { get; set; }
    [JsonProperty("mode")]
    public string Mode { get; set; }
    [JsonProperty("branch", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Branch { get; set; }
    [JsonProperty("path", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Path { get; set; }
    [JsonProperty("parentBranch", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? ParentBranch { get; set; }
}
