// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ChatCompletionRequestMessage
/// Discriminator: type = "requestChatCompletion"
/// Source: ..\..\..\..\src\services\autocomplete\chat-autocomplete\ChatTextAreaAutocomplete.ts
/// </summary>
public class ChatCompletionRequestMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "requestChatCompletion";
    [JsonProperty("text")]
    public string Text { get; set; }
    [JsonProperty("requestId")]
    public string RequestId { get; set; }
}
