// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: CloudSessionDataLoadedMessage
/// Discriminator: type = "cloudSessionDataLoaded"
/// Source: extension-messages.ts
/// </summary>
public class CloudSessionDataLoadedMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "cloudSessionDataLoaded";
    [JsonProperty("cloudSessionId")]
    public string CloudSessionId { get; set; }
    [JsonProperty("title")]
    public string Title { get; set; }
    [JsonProperty("messages")]
    public List<Message> Messages { get; set; }
}
