// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: CloudSessionsLoadedMessage
/// Discriminator: type = "cloudSessionsLoaded"
/// Source: extension-messages.ts
/// </summary>
public class CloudSessionsLoadedMessage
{
    public string Type { get; set; }
    [JsonProperty("sessions")]
    public List<CloudSessionInfo> Sessions { get; set; }
    [JsonProperty("nextCursor", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: null | string
    public string? NextCursor { get; set; }
}
