// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ImportResultMessage
/// Discriminator: type = "agentManager.importResult"
/// Source: ..\..\..\..\src\agent-manager\types.ts
/// </summary>
public class ImportResultMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.importResult";
    [JsonProperty("success")]
    // Original TypeScript type: literal
    public string Success { get; set; }
    [JsonProperty("message")]
    public string Message { get; set; }
    [JsonProperty("errorCode", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | "git_not_found" | "not_git_repo" | "lfs_missing" | "no_commits"
    public object? ErrorCode { get; set; }
}
