// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ImportExternalWorktreeRequest
/// Discriminator: type = "agentManager.importExternalWorktree"
/// Source: webview-messages.ts
/// </summary>
public class ImportExternalWorktreeRequest
{
    public string Type { get; set; }
    [JsonProperty("path")]
    public string Path { get; set; }
    [JsonProperty("branch")]
    public string Branch { get; set; }
}
