// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: InlineTerminalContextResultMessage
/// Discriminator: type = "terminalContextResult"
/// Source: KiloProvider.ts
/// </summary>
public class InlineTerminalContextResultMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "terminalContextResult";
    [JsonProperty("content")]
    public string Content { get; set; }
    [JsonProperty("truncated")]
    public bool Truncated { get; set; }
}
