// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: InlineDiffViewer.diffsMessage
/// Discriminator: type = "diffViewer.diffs"
/// Source: diff\DiffViewerProvider.ts
/// </summary>
public class InlineDiffViewerdiffsMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "diffViewer.diffs";
    [JsonProperty("diffs")]
    public List<object> Diffs { get; set; }
}
