// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: MessagesLoadedMessage
/// Discriminator: type = "messagesLoaded"
/// Source: extension-messages.ts
/// </summary>
public class MessagesLoadedMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "messagesLoaded";
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
    [JsonProperty("messages")]
    public List<Message> Messages { get; set; }
    [JsonProperty("mode", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | "replace" | "prepend" | "reconcile"
    public object? Mode { get; set; }
    [JsonProperty("cursor", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Cursor { get; set; }
    [JsonProperty("hasMore", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public object? HasMore { get; set; }
    [JsonProperty("since", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? Since { get; set; }
}
