// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: NotificationsLoadedMessage
/// Discriminator: type = "notificationsLoaded"
/// Source: extension-messages.ts
/// </summary>
public class NotificationsLoadedMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "notificationsLoaded";
    [JsonProperty("notifications")]
    public List<KilocodeNotification> Notifications { get; set; }
    [JsonProperty("dismissedIds")]
    public List<string> DismissedIds { get; set; }
}
