// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SendMessageFailedMessage
/// Discriminator: type = "sendMessageFailed"
/// Source: extension-messages.ts
/// </summary>
public class SendMessageFailedMessage
{
    [JsonProperty("type")]
    public string Type { get; set; }
    [JsonProperty("error")]
    public string Error { get; set; }
    [JsonProperty("text")]
    public string Text { get; set; }
    [JsonProperty("sessionID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? SessionID { get; set; }
    [JsonProperty("draftID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? DraftID { get; set; }
    [JsonProperty("messageID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? MessageID { get; set; }
    [JsonProperty("files", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | Array
    public object? Files { get; set; }
    [JsonProperty("review", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | ReviewMessageData
    public ReviewMessageData? Review { get; set; }
}
