// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SessionsLoadedMessage
/// Discriminator: type = "sessionsLoaded"
/// Source: extension-messages.ts
/// </summary>
public class SessionsLoadedMessage
{
    public string Type { get; set; }
    [JsonProperty("sessions")]
    public List<SessionInfo> Sessions { get; set; }
    [JsonProperty("preserveSessionIds", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | Array
    public object? PreserveSessionIds { get; set; }
}
