// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SkillsLoadedMessage
/// Discriminator: type = "skillsLoaded"
/// Source: extension-messages.ts
/// </summary>
public class SkillsLoadedMessage
{
    [JsonProperty("type")]
    public string Type { get; set; }
    [JsonProperty("skills")]
    public List<SkillInfo> Skills { get; set; }
}
