// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: TerminalResizeIn
/// Discriminator: type = "agentManager.terminal.resize"
/// Source: ..\..\..\..\src\agent-manager\types.ts
/// </summary>
public class TerminalResizeIn
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.terminal.resize";
    [JsonProperty("terminalId")]
    public string TerminalId { get; set; }
    [JsonProperty("cols")]
    public double Cols { get; set; }
    [JsonProperty("rows")]
    public double Rows { get; set; }
}
