// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: WorktreeDiffMessage
/// Discriminator: type = "agentManager.worktreeDiff"
/// Source: ..\..\..\..\src\agent-manager\types.ts
/// </summary>
public class WorktreeDiffMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.worktreeDiff";
    [JsonProperty("sessionId")]
    public string SessionId { get; set; }
    [JsonProperty("diffs")]
    public List<object> Diffs { get; set; }
}
