// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ChatCompletionAcceptedMessage
/// Discriminator: type = "chatCompletionAccepted"
/// Source: webview-messages.ts
/// </summary>
public class ChatCompletionAcceptedMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "chatCompletionAccepted";
    [JsonProperty("suggestionLength", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? SuggestionLength { get; set; }
}
