// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SetSessionsCollapsedRequest
/// Discriminator: type = "agentManager.setSessionsCollapsed"
/// Source: webview-messages.ts
/// </summary>
public class SetSessionsCollapsedRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agentManager.setSessionsCollapsed";
    [JsonProperty("collapsed")]
    public bool Collapsed { get; set; }
}
