// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ToggleFavoriteRequest
/// Discriminator: type = "toggleFavorite"
/// Source: webview-messages.ts
/// </summary>
public class ToggleFavoriteRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "toggleFavorite";
    [JsonProperty("action", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: add | remove
    public object? Action { get; set; }
    [JsonProperty("providerID")]
    public string ProviderID { get; set; }
    [JsonProperty("modelID")]
    public string ModelID { get; set; }
}
