// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.sessions;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: SessionUpdate
/// Source: sessions.ts
/// </summary>
public class SessionUpdate : SessionInfo
{
    [JsonProperty("id")]
    public string Id { get; set; }
}
