//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Parts;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: BasePart
/// Source: parts.ts
/// </summary>
public partial class BasePart
{
    [JsonProperty("id")]
    public string Id { get; set; }
    [JsonProperty("sessionID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? SessionID { get; set; }
    [JsonProperty("messageID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? MessageID { get; set; }
}
