//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Parts;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: ContextUsage
/// Source: parts.ts
/// </summary>
public partial class ContextUsage
{
    [JsonProperty("tokens")]
    public double Tokens { get; set; }
    [JsonProperty("percentage", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: null | number
    public double? Percentage { get; set; }
}
