// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Parts;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: FilePartSource
/// Discriminator: type = "file"
/// Source: parts.ts
/// Signature hash: 95e490faa353aace5fbff94b81edc12a5143d3e69ad34b74d12b58d4d05055c7
/// </summary>
public class FilePartSource
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "file";
    [JsonProperty("path")]
    public string Path { get; set; }
    [JsonProperty("text")]
    // Original TypeScript type: textType
    public TextType Text { get; set; }
}
