// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Parts;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: FilePart
/// Discriminator: type = "file"
/// Source: parts.ts
/// Signature hash: df3eb60ebe5520b3ebb029e2c55d9b538e4989479ee7137e7eed4007c32eff63
/// </summary>
public class FilePart : BasePart, IPart
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "file";
    [JsonProperty("mime")]
    public string Mime { get; set; }
    [JsonProperty("url")]
    public string Url { get; set; }
    [JsonProperty("filename", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Filename { get; set; }
    [JsonProperty("source", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | FilePartSource
    public FilePartSource? Source { get; set; }
}
