// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Parts;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: PartDelta
/// Discriminator: type = "text-delta"
/// Source: parts.ts
/// Signature hash: 54969db1945d8454baf4c995c2f783db2202f31dccfddd421610f34baf076801
/// </summary>
public partial class PartDelta : IWebviewMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "text-delta";
    [JsonProperty("textDelta", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? TextDelta { get; set; }
}
