// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Parts;

/// <summary>
/// Type: Part (placeholder for union)
/// Source: parts.ts
/// </summary>
public partial class Part { }
