//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Parts;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: StepStartPartTimeType
/// Source: parts.ts
/// Signature hash: b7ff3c82e1481ab938913125b2393cba323fe3947bbf2365afa0820547a8795d
/// </summary>
public partial class StepStartPartTimeType
{
    [JsonProperty("start")]
    public double Start { get; set; }
}
