//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Parts;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: StepFinishPartTokensType
/// Source: parts.ts
/// Signature hash: fd3afcc7a64998468674b1274de1af7dc53893577aae1da60a0353bb19e377db
/// </summary>
public partial class StepFinishPartTokensType
{
    [JsonProperty("input")]
    public double Input { get; set; }
    [JsonProperty("output")]
    public double Output { get; set; }
    [JsonProperty("reasoning", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? Reasoning { get; set; }
    [JsonProperty("cache", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: cacheType
    public CacheType? Cache { get; set; }
}
