//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Parts;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: textType
/// Source: parts.ts
/// </summary>
public class TextType
{
    [JsonProperty("value")]
    public string Value { get; set; }
    [JsonProperty("start")]
    public double Start { get; set; }
    [JsonProperty("end")]
    public double End { get; set; }
}
