//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Parts;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: TextPartTimeType
/// Source: Shared\parts.ts
/// Signature hash: 12fc3674e2a370589374eb4b8ac52a9a4fc83a114159a62a688270324e4a1b05
/// </summary>
public partial class TextPartTimeType
{
    [JsonProperty("start")]
    public double Start { get; set; }
    [JsonProperty("end", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? End { get; set; }
}
