//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Sessions;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: MessageErrorType
/// Source: Shared\sessions.ts
/// Signature hash: c24891cde040a72568b5b790add75d66132a1ea0da9fc05cd94f45de20b5d16c
/// </summary>
public partial class MessageErrorType : IWebviewMessage
{
    [JsonProperty("name")]
    public string Name { get; set; }
    [JsonProperty("data", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Data { get; set; }
}
