//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: AgentContentRequirementsType
/// Source: ..\marketplace.ts
/// Signature hash: a888a5bb8439ba9449f51cde35755b53223df7f1599c44ee44c9ca74577fb343
/// </summary>
public partial class AgentContentRequirementsType
{
    [JsonProperty("skills", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | Array
    public object? Skills { get; set; }
    [JsonProperty("mcps", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | Array
    public object? Mcps { get; set; }
    [JsonProperty("vscode_extensions", NullValueHandling = NullValueHandling.Ignore)]
    public List<Vscode_extensionsItemType>? Vscode_extensions { get; set; }
}
