// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Shared;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: AgentMarketplaceItem
/// Discriminator: type = "agent"
/// Source: ..\marketplace.ts
/// Signature hash: 510951ca7a4a854d49fe64660b24e1bb7a7b3cfd5c25ee93e8a79ee0e5dad3f6
/// </summary>
public partial class AgentMarketplaceItem : MarketplaceItemBase, IWebviewMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "agent";
    [JsonProperty("content")]
    // Original TypeScript type: AgentContent
    public AgentContent Content { get; set; }
}
