//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.ExtensionMessages;

/// <summary>
/// Part type: AnacondadesktopstatusresultMessage
/// Discriminator: type = "anacondaDesktopStatusResult"
/// Source: ..\..\..\..\src\shared\anaconda-desktop-messages.ts
/// Signature hash: c3de6e55f030a851f17065920f50cbf6924430955c7ddb3ccf079643d098f048
/// </summary>
public partial class AnacondadesktopstatusresultMessage : IExtensionMessage, IWebviewMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "anacondaDesktopStatusResult";
    [JsonProperty("requestId")]
    public string RequestId { get; set; }
    [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: __type | __type | __type | __type | __type | __type | __type | __type | __type | __type | __type
    public object? Status { get; set; }
}
