//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: AnacondaDesktopExtensionMessageStatusType
/// Source: ..\..\..\..\src\shared\anaconda-desktop-messages.ts
/// Signature hash: 9bb7d6f86acc86153fb30fe6dbe26cf9f7e24fce2a1939d8f404560b17705a0d
/// </summary>
public partial class AnacondaDesktopExtensionMessageStatusType : IWebviewMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; }
    [JsonProperty("serverID")]
    public string ServerID { get; set; }
    [JsonProperty("serverName", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? ServerName { get; set; }
    [JsonProperty("models")]
    // Original TypeScript type: vscode_extensionsItemType
    public Vscode_extensionsItemType Models { get; set; }
    [JsonProperty("context")]
    public double Context { get; set; }
    [JsonProperty("toolcall", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: supported | unsupported | unknown
    public object? Toolcall { get; set; }
}
