//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.ExtensionMessages;

/// <summary>
/// Part type: AnacondadesktopopenedMessage
/// Discriminator: type = "anacondaDesktopOpened"
/// Source: ..\..\..\..\src\shared\anaconda-desktop-messages.ts
/// Signature hash: 8fc0f60a3b9c8bd26aabcc1a7c3c3958a3b3c4c4d1c6c7f8cdbd9c0b04bb9134
/// </summary>
public partial class AnacondadesktopopenedMessage : IExtensionMessage, IWebviewMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "anacondaDesktopOpened";
    [JsonProperty("requestId")]
    public string RequestId { get; set; }
}
