//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.ExtensionMessages;

/// <summary>
/// Part type: AnacondadesktopsyncedMessage
/// Discriminator: type = "anacondaDesktopSynced"
/// Source: ..\..\..\..\src\shared\anaconda-desktop-messages.ts
/// Signature hash: c9ca5933505d5db86d9bf4c9d217c494371157fa23a06a76d9f38e5598d7f93b
/// </summary>
public partial class AnacondadesktopsyncedMessage : IExtensionMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "anacondaDesktopSynced";
    [JsonProperty("requestId")]
    public string RequestId { get; set; }
    [JsonProperty("status")]
    // Original TypeScript type: __type
    public object Status { get; set; }
}
