//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: captureType
/// Source: ..\..\..\..\..\sdk\js\src\v2\gen\types.gen.ts
/// </summary>
public class CaptureType
{
    [JsonProperty("mode")]
    // Original TypeScript type: literal
    public string Mode { get; set; }
    [JsonProperty("turnClose")]
    public bool TurnClose { get; set; }
    [JsonProperty("explicit")]
    public bool Explicit { get; set; }
    [JsonProperty("maxOpsPerRun")]
    public double MaxOpsPerRun { get; set; }
    [JsonProperty("minIntervalMs")]
    public double MinIntervalMs { get; set; }
    [JsonProperty("timeoutMs")]
    public double TimeoutMs { get; set; }
}
