// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

/// <summary>
/// Enum: ExpandedCollapsedEnum
/// Generated from inline string literal union
/// Members: collapsed, expanded
/// Used by: WorkStyleConfig
/// </summary>
[JsonConverter(typeof(StringEnumConverter))]
public enum ExpandedCollapsedEnum
{
    [JsonProperty("collapsed")]
    Collapsed,
    [JsonProperty("expanded")]
    Expanded
}
