// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.OrchestrationDomain;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

/// <summary>
/// Enum: FailureCodeEnum
/// Generated from union type
/// </summary>
[JsonConverter(typeof(StringEnumConverter))]
public enum FailureCodeEnum
{
    [JsonProperty("cross_workspace")]
    Cross_workspace,
    [JsonProperty("host_error")]
    Host_error,
    [JsonProperty("stale_session")]
    Stale_session,
    [JsonProperty("unavailable_session")]
    Unavailable_session,
    [JsonProperty("unknown_session")]
    Unknown_session,
    [JsonProperty("workspace_unavailable")]
    Workspace_unavailable
}
