// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Types;

/// <summary>
/// Union Marker: AgentManagerInMessage
/// Member count: 71
/// Source: agent-manager\types.ts
/// </summary>
public interface IAgentManagerInMessage: IWebviewMessage
{
}
