// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.AnacondaDesktopMessages;

/// <summary>
/// Union Marker: AnacondaDesktopExtensionMessage
/// Member count: 3
/// Source: shared\anaconda-desktop-messages.ts
/// </summary>
public interface IAnacondaDesktopExtensionMessage
{
}
