// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Types;

/// <summary>
/// Union Marker: NotebookEdit
/// Member count: 4
/// Source: services\notebook\types.ts
/// </summary>
public interface INotebookEdit
{
}
