//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: InstallMarketplaceItemOptions
/// Source: ..\marketplace.ts
/// </summary>
public partial class InstallMarketplaceItemOptions : IWebviewMessage
{
    [JsonProperty("target", NullValueHandling = NullValueHandling.Ignore)]
    public GlobalProjectEnum? Target { get; set; }
    [JsonProperty("parameters", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Parameters { get; set; }
}
