// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.NextEditSuggestionManager;

/// <summary>
/// Union Marker: PendingNextEdit
/// Member count: 2
/// Source: services\autocomplete\next-edit\NextEditSuggestionManager.ts
/// </summary>
public interface IPendingNextEdit: IWebviewMessage
{
}
