// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.AgentRequirements;

/// <summary>
/// Union Marker: RequirementErrorCode
/// Member count: 6
/// Source: kilo-provider\agent-requirements.ts
/// </summary>
public interface IRequirementErrorCode: IWebviewMessage
{
}
