// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Transcribe;

/// <summary>
/// Union Marker: SpeechToTextResult
/// Member count: 1
/// Source: speech-to-text\transcribe.ts
/// </summary>
public interface ISpeechToTextResult: IWebviewMessage
{
}
