//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: limitsType
/// Source: ..\..\..\..\..\sdk\js\src\v2\gen\types.gen.ts
/// </summary>
public class LimitsType
{
    [JsonProperty("maxProjectIndexBytes")]
    public double MaxProjectIndexBytes { get; set; }
    [JsonProperty("maxSessionFiles")]
    public double MaxSessionFiles { get; set; }
    [JsonProperty("maxRecentSessions")]
    public double MaxRecentSessions { get; set; }
    [JsonProperty("maxConsolidationInputBytes")]
    public double MaxConsolidationInputBytes { get; set; }
    [JsonProperty("maxLineChars")]
    public double MaxLineChars { get; set; }
    [JsonProperty("maxSessionLineChars")]
    public double MaxSessionLineChars { get; set; }
}
