//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: MemoryOperationResponseStateType
/// Source: ..\..\..\..\..\sdk\js\src\v2\gen\types.gen.ts
/// Signature hash: 302787dbd8d8eb0c6bc8491315541e7ccbde520592590a29ff1568d06a0644fa
/// </summary>
public partial class MemoryOperationResponseStateType : IWebviewMessage
{
    [JsonProperty("version")]
    // Original TypeScript type: literal
    public double Version { get; set; }
    [JsonProperty("enabled")]
    public bool Enabled { get; set; }
    [JsonProperty("scope")]
    // Original TypeScript type: literal
    public string Scope { get; set; }
    [JsonProperty("autoInject")]
    public bool AutoInject { get; set; }
    [JsonProperty("autoConsolidate")]
    public bool AutoConsolidate { get; set; }
    [JsonProperty("verbose")]
    public bool Verbose { get; set; }
    [JsonProperty("capture")]
    // Original TypeScript type: MemoryShowResponseCaptureType
    public MemoryShowResponseCaptureType Capture { get; set; }
    [JsonProperty("limits")]
    // Original TypeScript type: limitsType
    public LimitsType Limits { get; set; }
    [JsonProperty("stats")]
    // Original TypeScript type: statsType
    public StatsType Stats { get; set; }
    /// <summary>
    /// Nested type: MemoryShowResponseCaptureType
    /// </summary>
    public partial class MemoryShowResponseCaptureType
    {
        [JsonProperty("mode")]
        // Original TypeScript type: literal
        public string Mode { get; set; }
        [JsonProperty("turnClose")]
        public bool TurnClose { get; set; }
        [JsonProperty("explicit")]
        public bool Explicit { get; set; }
        [JsonProperty("maxOpsPerRun")]
        public double MaxOpsPerRun { get; set; }
        [JsonProperty("minIntervalMs")]
        public double MinIntervalMs { get; set; }
        [JsonProperty("timeoutMs")]
        public double TimeoutMs { get; set; }
    }

}
