//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: MemoryOperationResponseIndexType
/// Source: ..\..\..\..\..\sdk\js\src\v2\gen\types.gen.ts
/// Signature hash: d77ca9eec0a3ef251832b0a96f42012d8f4a47a492c19191663f21887ad72d95
/// </summary>
public partial class MemoryOperationResponseIndexType
{
    [JsonProperty("text")]
    public string Text { get; set; }
    [JsonProperty("bytes")]
    public double Bytes { get; set; }
    [JsonProperty("tokens")]
    public double Tokens { get; set; }
    [JsonProperty("truncated")]
    public bool Truncated { get; set; }
}
