//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: MemoryOperationResponseSkippedItemType
/// Source: ..\..\..\..\..\sdk\js\src\v2\gen\types.gen.ts
/// Signature hash: 67091578b33ccaf7f75c63ed68a1f0ce1b4ab79e63f6b5900c7100b5d935478f
/// </summary>
public partial class MemoryOperationResponseSkippedItemType
{
    [JsonProperty("reason", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: self_referential | out_of_scope | secret
    public object? Reason { get; set; }
    [JsonProperty("text", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Text { get; set; }
}
