//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: MemoryOperationResponseExistsType
/// Source: ..\..\..\..\..\sdk\js\src\v2\gen\types.gen.ts
/// Signature hash: 04ba0c0c10f9fd8851a168ad1a3fb56bd9a424a08afe3727831a79b105decc7d
/// </summary>
public partial class MemoryOperationResponseExistsType
{
    [JsonProperty("state")]
    public bool State { get; set; }
    [JsonProperty("index")]
    public bool Index { get; set; }
}
