//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Part type: PartUpdate
/// Discriminator: type = "partUpdated"
/// Source: ..\..\..\..\src\shared\stream-messages.ts
/// </summary>
public class PartUpdate
{
    [JsonProperty("type")]
    // Original TypeScript type: stringLiteral
    public string Type { get; set; } = "partUpdated";
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
    [JsonProperty("messageID")]
    public string MessageID { get; set; }
    [JsonProperty("part")]
    public object Part { get; set; }
    [JsonProperty("delta", NullValueHandling = NullValueHandling.Ignore)]
    public object? Delta { get; set; }
}
