// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.AgentRequirements;

/// <summary>
/// Enum: RequirementErrorCode
/// Generated from union type
/// </summary>
public enum RequirementErrorCode
{
    Unknown_agent,
    Malformed_declaration,
    Discovery_failed,
    Mcp_status_failed,
    Scope_mismatch,
    Request_failed
}
