// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.AgentRequirements;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

/// <summary>
/// Enum: RequirementErrorCodeEnum
/// Generated from union type
/// </summary>
[JsonConverter(typeof(StringEnumConverter))]
public enum RequirementErrorCodeEnum
{
    [JsonProperty("unknown_agent")]
    Unknown_agent,
    [JsonProperty("malformed_declaration")]
    Malformed_declaration,
    [JsonProperty("discovery_failed")]
    Discovery_failed,
    [JsonProperty("mcp_status_failed")]
    Mcp_status_failed,
    [JsonProperty("scope_mismatch")]
    Scope_mismatch,
    [JsonProperty("request_failed")]
    Request_failed
}
