// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Shared;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SkillMarketplaceItem
/// Discriminator: type = "skill"
/// Source: ..\marketplace.ts
/// Signature hash: 753a6bb40fcce57a00937f08f77e7746aec3b32344b89af43fa3966242ace61c
/// </summary>
public partial class SkillMarketplaceItem : MarketplaceItemBase, IWebviewMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "skill";
    [JsonProperty("githubUrl")]
    public string GithubUrl { get; set; }
    [JsonProperty("content")]
    public string Content { get; set; }
    [JsonProperty("displayName")]
    public string DisplayName { get; set; }
    [JsonProperty("displayCategory")]
    public string DisplayCategory { get; set; }
}
