//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: stateType
/// Source: ..\..\..\..\..\sdk\js\src\v2\gen\types.gen.ts
/// </summary>
public class StateType
{
    [JsonProperty("version")]
    // Original TypeScript type: literal
    public double Version { get; set; }
    [JsonProperty("enabled")]
    public bool Enabled { get; set; }
    [JsonProperty("scope")]
    // Original TypeScript type: literal
    public string Scope { get; set; }
    [JsonProperty("autoInject")]
    public bool AutoInject { get; set; }
    [JsonProperty("autoConsolidate")]
    public bool AutoConsolidate { get; set; }
    [JsonProperty("verbose")]
    public bool Verbose { get; set; }
    [JsonProperty("capture")]
    // Original TypeScript type: captureType
    public CaptureType Capture { get; set; }
    [JsonProperty("limits")]
    // Original TypeScript type: limitsType
    public LimitsType Limits { get; set; }
    [JsonProperty("stats")]
    // Original TypeScript type: statsType
    public StatsType Stats { get; set; }
}
