//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: statsType
/// Source: ..\..\..\..\..\sdk\js\src\v2\gen\types.gen.ts
/// </summary>
public class StatsType
{
    [JsonProperty("lastInjectedAt")]
    public double LastInjectedAt { get; set; }
    [JsonProperty("lastInjectedBytes")]
    public double LastInjectedBytes { get; set; }
    [JsonProperty("lastInjectedTokens")]
    public double LastInjectedTokens { get; set; }
    [JsonProperty("lastInjectedSessionID")]
    public string LastInjectedSessionID { get; set; }
    [JsonProperty("lastTypedConsolidationAt")]
    public double LastTypedConsolidationAt { get; set; }
    [JsonProperty("lastSessionSavedAt")]
    public double LastSessionSavedAt { get; set; }
    [JsonProperty("lastConsolidationCost")]
    public double LastConsolidationCost { get; set; }
    [JsonProperty("lastConsolidationTokens")]
    public double LastConsolidationTokens { get; set; }
    [JsonProperty("lastOperationCount")]
    public double LastOperationCount { get; set; }
    [JsonProperty("lastRecallAt")]
    public double LastRecallAt { get; set; }
    [JsonProperty("lastRecallCount")]
    public double LastRecallCount { get; set; }
    [JsonProperty("lastRecallSessionID")]
    public string LastRecallSessionID { get; set; }
}
