//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: updatesItemType
/// Source: ..\..\..\..\src\shared\stream-messages.ts
/// </summary>
public class UpdatesItemType
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; }
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
    [JsonProperty("messageID")]
    public string MessageID { get; set; }
    [JsonProperty("part")]
    // Original TypeScript type: P
    public object Part { get; set; }
    [JsonProperty("delta", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Delta { get; set; }
}
