//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: WorkStyleApplyPlan
/// Source: ..\..\..\..\src\shared\work-style-presets.ts
/// </summary>
public partial class WorkStyleApplyPlan
{
    [JsonProperty("config")]
    // Original TypeScript type: WorkStyleConfig
    public WorkStyleConfig Config { get; set; }
    [JsonProperty("settings")]
    // Original TypeScript type: __type
    public object Settings { get; set; }
}
