//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Connection;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Part type: BusyMessage
/// Discriminator: type = "busy"
/// Source: connection.ts
/// Signature hash: dfc0b95a7f6ff65f545fe29dec04cf82afbc7af4c8e8045c5a116ce12efcbbb8
/// </summary>
public class BusyMessage : ISessionStatusInfo
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "busy";
}
