// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Connection;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

/// <summary>
/// Enum: DeviceAuthStatusEnum
/// Generated from union type
/// </summary>
[JsonConverter(typeof(StringEnumConverter))]
public enum DeviceAuthStatusEnum
{
    [JsonProperty("success")]
    Success,
    [JsonProperty("pending")]
    Pending,
    [JsonProperty("cancelled")]
    Cancelled,
    [JsonProperty("idle")]
    Idle,
    [JsonProperty("error")]
    Error,
    [JsonProperty("initiating")]
    Initiating
}
