//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Connection;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Part type: IdleMessage
/// Discriminator: type = "idle"
/// Source: connection.ts
/// Signature hash: 0ef3b6c7dbb371ccd02af40b601e51ae94a3fd41e789ed7fbbd1b2a84a12759b
/// </summary>
public class IdleMessage : ISessionStatusInfo
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "idle";
}
