// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.AgentManager;

/// <summary>
/// Union Marker: WorktreeErrorCode
/// Member count: 3
/// Source: agent-manager.ts
/// </summary>
public interface IWorktreeErrorCode
{
}
