//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.AgentManager;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: PRStatusChecksType
/// Source: agent-manager.ts
/// Signature hash: 094030a57bc0d9eca7eabec6133166ced8e9f7e4acfa810882347cb94b143d1c
/// </summary>
public partial class PRStatusChecksType : IWebviewMessage
{
    [JsonProperty("status")]
    // Original TypeScript type: AggregateCheckStatus
    public AggregateCheckStatusEnum Status { get; set; }
    [JsonProperty("total")]
    public double Total { get; set; }
    [JsonProperty("passed")]
    public double Passed { get; set; }
    [JsonProperty("failed")]
    public double Failed { get; set; }
    [JsonProperty("pending")]
    public double Pending { get; set; }
    [JsonProperty("items")]
    public List<PRCheck> Items { get; set; }
}
