// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.AgentManager;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

/// <summary>
/// Enum: ReviewDecisionEnum
/// Generated from union type
/// Source: agent-manager.ts
/// </summary>
[JsonConverter(typeof(StringEnumConverter))]
public enum ReviewDecisionEnum
{
    [JsonProperty("pending")]
    Pending,
    [JsonProperty("approved")]
    Approved,
    [JsonProperty("changes_requested")]
    Changes_requested
}
