// <auto-generated>
//     Additional properties for RequestGitChangesContextMessage.
//     These fields are added by the VS Code extension at runtime.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.WebviewMessages;

using Newtonsoft.Json;

/// <summary>
/// Partial class extension for RequestGitChangesContextMessage.
/// Adds runtime-added properties from VS Code extension.
/// </summary>
public partial class RequestGitChangesContextMessage
{
    /// <summary>
    /// The context directory for git changes.
    /// Added by VS Code extension during message processing.
    /// </summary>
    [JsonProperty("contextDirectory", NullValueHandling = NullValueHandling.Ignore)]
    public string? ContextDirectory { get; set; }

    /// <summary>
    /// The base branch for git changes comparison.
    /// Added by VS Code extension during message processing.
    /// </summary>
    [JsonProperty("gitChangesBase", NullValueHandling = NullValueHandling.Ignore)]
    public string? GitChangesBase { get; set; }
}
