//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.AgentManager;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: PRComment
/// Source: agent-manager.ts
/// </summary>
public class PRComment
{
    [JsonProperty("id")]
    public string Id { get; set; }
    [JsonProperty("author")]
    public string Author { get; set; }
    [JsonProperty("avatar", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Avatar { get; set; }
    [JsonProperty("body")]
    public string Body { get; set; }
    [JsonProperty("file", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? File { get; set; }
    [JsonProperty("line", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? Line { get; set; }
    [JsonProperty("url", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Url { get; set; }
    [JsonProperty("resolved")]
    public bool Resolved { get; set; }
    [JsonProperty("createdAt", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? CreatedAt { get; set; }
}
