// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated.agentManager;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: TerminalFont
/// Source: agent-manager.ts
/// </summary>
public class TerminalFont
{
    [JsonProperty("fontFamily")]
    public string FontFamily { get; set; }
    [JsonProperty("fontSize")]
    public double FontSize { get; set; }
}
