//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Providers;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.Parts;

/// <summary>
/// Type: costType
/// Source: providers.ts
/// </summary>
public class CostType
{
    [JsonProperty("input")]
    public double Input { get; set; }
    [JsonProperty("output")]
    public double Output { get; set; }
    [JsonProperty("cache", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: cacheType
    public CacheType? Cache { get; set; }
}
