//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Providers;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: inputType
/// Source: providers.ts
/// Signature hash: 8e17bf40cfeed0c745ec2d91d21c5d13598afd62e0d42a01c6407cc83f54f578
/// </summary>
public partial class InputType
{
    [JsonProperty("text")]
    public bool Text { get; set; }
    [JsonProperty("image")]
    public bool Image { get; set; }
    [JsonProperty("audio")]
    public bool Audio { get; set; }
    [JsonProperty("video")]
    public bool Video { get; set; }
    [JsonProperty("pdf")]
    public bool Pdf { get; set; }
}
