//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Providers;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;
using KiloExtensionDTOs.Parts;

/// <summary>
/// Type: ProviderModelCostType
/// Source: providers.ts
/// Signature hash: 625d14ff5b79ec87f73af2c37041a500e5021ddbcb8ee2c03339651a6c0d395f
/// </summary>
public partial class ProviderModelCostType : IWebviewMessage
{
    [JsonProperty("input")]
    public double Input { get; set; }
    [JsonProperty("output")]
    public double Output { get; set; }
    [JsonProperty("cache", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: cacheType
    public CacheType? Cache { get; set; }
}
