//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Providers;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: ProviderMetadataType
/// Source: providers.ts
/// Signature hash: a645b5b0284e8258f8519ef5305c283bdc47671595933c36adcf514f7ddb3bd4
/// </summary>
public partial class ProviderMetadataType
{
    [JsonProperty("noteKey", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? NoteKey { get; set; }
    [JsonProperty("icon", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Icon { get; set; }
    [JsonProperty("priority", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? Priority { get; set; }
}
