//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
// </auto-generated>

#nullable enable

namespace KiloExtensionDTOs.Providers;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// Type: ProviderModelCapabilitiesType
/// Source: providers.ts
/// Signature hash: 3f08b85a8625a751dff90ec0958ab1cedba05de6f04f5c74aa055e1f2285c1be
/// </summary>
public partial class ProviderModelCapabilitiesType
{
    [JsonProperty("reasoning")]
    public bool Reasoning { get; set; }
    [JsonProperty("input", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: inputType
    public InputType? Input { get; set; }
}
