// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: Auth
/// Discriminator: type = "apiKey"
/// Source: ..\..\..\..\..\sdk\js\src\v2\gen\core\auth.gen.ts
/// </summary>
public class Auth
{
    [JsonProperty("in", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | "header" | "query" | "cookie"
    public object? In { get; set; }
    [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Name { get; set; }
    [JsonProperty("scheme", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | "basic" | "bearer"
    public object? Scheme { get; set; }
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "apiKey";
}
