// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ContextProviderDescription
/// Discriminator: type = "normal"
/// Source: ..\..\..\..\src\services\autocomplete\continuedev\core\index.d.ts
/// </summary>
public class ContextProviderDescription
{
    [JsonProperty("title")]
    public string Title { get; set; }
    [JsonProperty("displayTitle")]
    public string DisplayTitle { get; set; }
    [JsonProperty("description")]
    public string Description { get; set; }
    [JsonProperty("renderInlineAs", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? RenderInlineAs { get; set; }
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "normal";
    [JsonProperty("dependsOnIndexing", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | Array
    public object? DependsOnIndexing { get; set; }
}
