// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: CronController
/// Discriminator: type = "scheduled"
/// Source: ..\..\..\..\..\kilo-visualstudio\tools\webview-contract-extractor\node_modules\bun-types\bun.d.ts
/// </summary>
public class CronController
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "scheduled";
    [JsonProperty("cron")]
    public string Cron { get; set; }
    [JsonProperty("scheduledTime")]
    public double ScheduledTime { get; set; }
}
