// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: CryptoKey
/// Discriminator: type = "private"
/// Source: ..\..\..\..\..\kilo-visualstudio\tools\webview-contract-extractor\node_modules\@types\node\crypto.d.ts
/// </summary>
public class CryptoKey
{
    [JsonProperty("algorithm")]
    public KeyAlgorithm Algorithm { get; set; }
    [JsonProperty("extractable")]
    public string Extractable { get; set; }
    public string Type { get; set; }
    [JsonProperty("usages")]
    public List<object> Usages { get; set; }
}
