// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: DirectUnderlyingSource
/// Discriminator: type = "direct"
/// Source: ..\..\..\..\..\kilo-visualstudio\tools\webview-contract-extractor\node_modules\bun-types\bun.d.ts
/// </summary>
public class DirectUnderlyingSource
{
    [JsonProperty("cancel", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | UnderlyingSourceCancelCallback
    public object? Cancel { get; set; }
    [JsonProperty("pull")]
    // Original TypeScript type: __type
    public object Pull { get; set; }
    public string Type { get; set; }
}
