// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: EncodedAudioChunk
/// Discriminator: type = "delta"
/// Source: ..\..\..\..\..\kilo-visualstudio\tools\webview-contract-extractor\node_modules\typescript\lib\lib.dom.d.ts
/// </summary>
public class EncodedAudioChunk
{
    [JsonProperty("byteLength")]
    public double ByteLength { get; set; }
    [JsonProperty("duration", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: null | number
    public double? Duration { get; set; }
    [JsonProperty("timestamp")]
    public double Timestamp { get; set; }
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "delta";
}
