// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: FetchCustomProviderModelsMessage
/// Discriminator: type = "fetchCustomProviderModels"
/// Source: webview-messages.ts
/// </summary>
public class FetchCustomProviderModelsMessage
{
    [JsonProperty("type")]
    public string Type { get; set; }
    [JsonProperty("requestId")]
    public string RequestId { get; set; }
    [JsonProperty("baseURL")]
    public string BaseURL { get; set; }
    [JsonProperty("apiKey", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? ApiKey { get; set; }
    [JsonProperty("providerID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? ProviderID { get; set; }
    [JsonProperty("headers", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Headers { get; set; }
}
