// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: FilePart
/// Discriminator: type = "file"
/// Source: ..\..\..\..\..\sdk\js\src\gen\types.gen.ts
/// </summary>
public class FilePart
{
    [JsonProperty("id")]
    public string Id { get; set; }
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
    [JsonProperty("messageID")]
    public string MessageID { get; set; }
    [JsonProperty("type")]
    // Original TypeScript type: unknown
    public string Type { get; set; } = "file";
    [JsonProperty("mime")]
    public string Mime { get; set; }
    [JsonProperty("filename", NullValueHandling = NullValueHandling.Ignore)]
    public string? Filename { get; set; }
    [JsonProperty("url")]
    public string Url { get; set; }
    [JsonProperty("source", NullValueHandling = NullValueHandling.Ignore)]
    public object? Source { get; set; }
}
