// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: FileEntry
/// Discriminator: status = "added"
/// Source: ..\..\..\..\src\diff\sources\git-status.ts
/// </summary>
public class FileEntry
{
    [JsonProperty("file")]
    public string File { get; set; }
    [JsonProperty("status")]
    // Original TypeScript type: literal
    public string Status { get; set; } = "added";
    [JsonProperty("additions")]
    public double Additions { get; set; }
    [JsonProperty("deletions")]
    public double Deletions { get; set; }
    [JsonProperty("tracked")]
    // Original TypeScript type: literal
    public string Tracked { get; set; }
    [JsonProperty("binary")]
    // Original TypeScript type: literal
    public string Binary { get; set; }
    [JsonProperty("stamp", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Stamp { get; set; }
}
