// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ImportAndSendMessage
/// Discriminator: type = "importAndSend"
/// Source: webview-messages.ts
/// </summary>
public class ImportAndSendMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "importAndSend";
    [JsonProperty("cloudSessionId")]
    public string CloudSessionId { get; set; }
    [JsonProperty("text")]
    public string Text { get; set; }
    [JsonProperty("messageID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? MessageID { get; set; }
    [JsonProperty("providerID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? ProviderID { get; set; }
    [JsonProperty("modelID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? ModelID { get; set; }
    [JsonProperty("agent", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Agent { get; set; }
    [JsonProperty("variant", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Variant { get; set; }
    [JsonProperty("files", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | Array
    public object? Files { get; set; }
    [JsonProperty("review", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | ReviewMessageData
    public ReviewMessageData? Review { get; set; }
    [JsonProperty("command", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Command { get; set; }
    [JsonProperty("commandArgs", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? CommandArgs { get; set; }
}
