// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: InlineConfigUpdateFailedMessage
/// Discriminator: type = "configUpdateFailed"
/// Source: KiloProvider.ts
/// </summary>
public class InlineConfigUpdateFailedMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "configUpdateFailed";
    [JsonProperty("message")]
    // Original TypeScript type: literal
    public string Message { get; set; }
}
