// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: InlineSandboxDefaultStatusMessage
/// Discriminator: type = "sandboxDefaultStatus"
/// Source: KiloProvider.ts
/// </summary>
public class InlineSandboxDefaultStatusMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "sandboxDefaultStatus";
    [JsonProperty("enabled")]
    public bool Enabled { get; set; }
    [JsonProperty("available")]
    public bool Available { get; set; }
    [JsonProperty("reason")]
    // Original TypeScript type: string | undefined
    public object Reason { get; set; }
}
