// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: InlineDeviceAuthStartedMessage
/// Discriminator: type = "deviceAuthStarted"
/// Source: kilo-provider\handlers\auth.ts
/// </summary>
public class InlineDeviceAuthStartedMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "deviceAuthStarted";
    [JsonProperty("verificationUrl")]
    public string VerificationUrl { get; set; }
    [JsonProperty("expiresIn")]
    // Original TypeScript type: literal
    public double ExpiresIn { get; set; }
}
