// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: InlineReadyMessage
/// Discriminator: type = "ready"
/// Source: KiloProvider.ts
/// </summary>
public class InlineReadyMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "ready";
    [JsonProperty("extensionVersion")]
    public object ExtensionVersion { get; set; }
    [JsonProperty("vscodeLanguage")]
    public string VscodeLanguage { get; set; }
    [JsonProperty("languageOverride")]
    // Original TypeScript type: string | undefined
    public object LanguageOverride { get; set; }
    [JsonProperty("workspaceDirectory")]
    // Original TypeScript type: string | undefined
    public object WorkspaceDirectory { get; set; }
}
