// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: IntegrationTextPrompt
/// Discriminator: type = "text"
/// Source: ..\..\..\..\..\sdk\js\src\v2\gen\types.gen.ts
/// </summary>
public class IntegrationTextPrompt
{
    [JsonProperty("type")]
    // Original TypeScript type: unknown
    public string Type { get; set; } = "text";
    [JsonProperty("key")]
    public string Key { get; set; }
    [JsonProperty("message")]
    public string Message { get; set; }
    [JsonProperty("placeholder", NullValueHandling = NullValueHandling.Ignore)]
    public string? Placeholder { get; set; }
    [JsonProperty("when", NullValueHandling = NullValueHandling.Ignore)]
    public object? When { get; set; }
}
