// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: McpMarketplaceItem
/// Discriminator: type = "mcp"
/// Source: ..\marketplace.ts
/// </summary>
public class McpMarketplaceItem
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "mcp";
    [JsonProperty("url")]
    public string Url { get; set; }
    [JsonProperty("content", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: string | Array
    public object? Content { get; set; }
    [JsonProperty("parameters", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | Array
    public object? Parameters { get; set; }
}
