// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: MediaDecodingConfiguration
/// Discriminator: type = "file"
/// Source: ..\..\..\..\..\kilo-visualstudio\tools\webview-contract-extractor\node_modules\typescript\lib\lib.dom.d.ts
/// </summary>
public class MediaDecodingConfiguration
{
    [JsonProperty("keySystemConfiguration", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | MediaCapabilitiesKeySystemConfiguration
    public MediaCapabilitiesKeySystemConfiguration? KeySystemConfiguration { get; set; }
    public string Type { get; set; }
}
