// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: MemoryOperationMessage
/// Discriminator: type = "memoryOperation"
/// Source: memory.ts
/// </summary>
public class MemoryOperationMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "memoryOperation";
    [JsonProperty("operation")]
    // Original TypeScript type: literal
    public string Operation { get; set; }
    [JsonProperty("sessionID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? SessionID { get; set; }
    [JsonProperty("mode", NullValueHandling = NullValueHandling.Ignore)]
    public StatusOnOff? Mode { get; set; }
    [JsonProperty("confirm", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public bool? Confirm { get; set; }
    [JsonProperty("text", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Text { get; set; }
    [JsonProperty("query", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Query { get; set; }
    [JsonProperty("key", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Key { get; set; }
    [JsonProperty("file", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | md" | md" | md"
    public object? File { get; set; }
    [JsonProperty("section", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Section { get; set; }
}
