// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: Message
/// Discriminator: role = "user"
/// Source: sessions.ts
/// </summary>
public class Message
{
    [JsonProperty("id")]
    public string Id { get; set; }
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
    [JsonProperty("role")]
    // Original TypeScript type: literal
    public string Role { get; set; } = "user";
    [JsonProperty("content", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Content { get; set; }
    [JsonProperty("parts", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | Array
    public object? Parts { get; set; }
    [JsonProperty("createdAt")]
    public string CreatedAt { get; set; }
    [JsonProperty("time", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Time { get; set; }
    [JsonProperty("agent", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Agent { get; set; }
    [JsonProperty("model", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Model { get; set; }
    [JsonProperty("providerID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? ProviderID { get; set; }
    [JsonProperty("modelID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? ModelID { get; set; }
    [JsonProperty("mode", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Mode { get; set; }
    [JsonProperty("parentID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? ParentID { get; set; }
    [JsonProperty("path", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Path { get; set; }
    [JsonProperty("error", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Error { get; set; }
    [JsonProperty("summary", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true | __type
    public object? Summary { get; set; }
    [JsonProperty("cost", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? Cost { get; set; }
    [JsonProperty("tokens", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | TokenUsage
    public TokenUsage? Tokens { get; set; }
    [JsonProperty("finish", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Finish { get; set; }
}
