// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: MigrationDataMessage
/// Discriminator: type = "migrationData"
/// Source: migration.ts
/// </summary>
public class MigrationDataMessage
{
    public string Type { get; set; }
    [JsonProperty("source")]
    public string Source { get; set; }
    [JsonProperty("operationId")]
    public string OperationId { get; set; }
    [JsonProperty("data")]
    // Original TypeScript type: __type
    public object Data { get; set; }
}
