// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: NextEditSuggestionEvent
/// Discriminator: status = "error"
/// Source: ..\..\..\..\src\services\autocomplete\next-edit\NextEditInlineCompletionProvider.ts
/// </summary>
public class NextEditSuggestionEvent
{
    [JsonProperty("shown")]
    // Original TypeScript type: literal
    public string Shown { get; set; }
    [JsonProperty("latencyMs")]
    public double LatencyMs { get; set; }
    [JsonProperty("status")]
    // Original TypeScript type: literal
    public string Status { get; set; } = "error";
    [JsonProperty("errorStatus", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? ErrorStatus { get; set; }
    [JsonProperty("inputTokens", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? InputTokens { get; set; }
    [JsonProperty("outputTokens", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | number
    public double? OutputTokens { get; set; }
}
