// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: OpenConfigFileRequest
/// Discriminator: type = "openConfigFile"
/// Source: webview-messages.ts
/// </summary>
public class OpenConfigFileRequest
{
    public string Type { get; set; }
    [JsonProperty("scope")]
    public string Scope { get; set; }
    [JsonProperty("labels")]
    // Original TypeScript type: __type
    public object Labels { get; set; }
}
