// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: OscillatorNode
/// Discriminator: type = "custom"
/// Source: ..\..\..\..\..\kilo-visualstudio\tools\webview-contract-extractor\node_modules\typescript\lib\lib.dom.d.ts
/// </summary>
public class OscillatorNode
{
    [JsonProperty("detune")]
    // Original TypeScript type: AudioParam
    public object Detune { get; set; }
    [JsonProperty("frequency")]
    // Original TypeScript type: AudioParam
    public object Frequency { get; set; }
    public string Type { get; set; }
}
