// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: OutputFormatJsonSchema
/// Discriminator: type = "json_schema"
/// Source: ..\..\..\..\..\sdk\js\src\v2\gen\types.gen.ts
/// </summary>
public class OutputFormatJsonSchema
{
    [JsonProperty("type")]
    public object Type { get; set; }
    [JsonProperty("schema")]
    public object Schema { get; set; }
    [JsonProperty("retryCount", NullValueHandling = NullValueHandling.Ignore)]
    public double? RetryCount { get; set; }
}
