// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ParseArgsOptionDescriptor
/// Discriminator: type = "string"
/// Source: ..\..\..\..\..\kilo-visualstudio\tools\webview-contract-extractor\node_modules\@types\node\util.d.ts
/// </summary>
public class ParseArgsOptionDescriptor
{
    public string Type { get; set; }
    [JsonProperty("multiple", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | false | true
    public object? Multiple { get; set; }
    [JsonProperty("short", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Short { get; set; }
    [JsonProperty("default", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string | false | true | Array | Array
    public object? Default { get; set; }
}
