// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: PerformanceNavigationTiming
/// Discriminator: type = "reload"
/// Source: ..\..\..\..\..\kilo-visualstudio\tools\webview-contract-extractor\node_modules\typescript\lib\lib.dom.d.ts
/// </summary>
public class PerformanceNavigationTiming
{
    [JsonProperty("domComplete")]
    public double DomComplete { get; set; }
    [JsonProperty("domContentLoadedEventEnd")]
    public double DomContentLoadedEventEnd { get; set; }
    [JsonProperty("domContentLoadedEventStart")]
    public double DomContentLoadedEventStart { get; set; }
    [JsonProperty("domInteractive")]
    public double DomInteractive { get; set; }
    [JsonProperty("loadEventEnd")]
    public double LoadEventEnd { get; set; }
    [JsonProperty("loadEventStart")]
    public double LoadEventStart { get; set; }
    [JsonProperty("redirectCount")]
    public double RedirectCount { get; set; }
    public string Type { get; set; }
    [JsonProperty("unloadEventEnd")]
    public double UnloadEventEnd { get; set; }
    [JsonProperty("unloadEventStart")]
    public double UnloadEventStart { get; set; }
}
