// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ReferenceGitSource
/// Discriminator: type = "git"
/// Source: ..\..\..\..\..\sdk\js\src\v2\gen\types.gen.ts
/// </summary>
public class ReferenceGitSource
{
    [JsonProperty("type")]
    public object Type { get; set; }
    [JsonProperty("repository")]
    public string Repository { get; set; }
    [JsonProperty("branch", NullValueHandling = NullValueHandling.Ignore)]
    public string? Branch { get; set; }
    [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore)]
    public string? Description { get; set; }
    [JsonProperty("hidden", NullValueHandling = NullValueHandling.Ignore)]
    public object? Hidden { get; set; }
}
