// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SandboxDefaultStatusMessage
/// Discriminator: type = "sandboxDefaultStatus"
/// Source: extension-messages.ts
/// </summary>
public class SandboxDefaultStatusMessage
{
    [JsonProperty("type")]
    public string Type { get; set; }
    [JsonProperty("desired")]
    public string Desired { get; set; }
    [JsonProperty("enabled")]
    public string Enabled { get; set; }
    [JsonProperty("available")]
    public string Available { get; set; }
    [JsonProperty("reason", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Reason { get; set; }
    [JsonProperty("revision")]
    public double Revision { get; set; }
    [JsonProperty("requestID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? RequestID { get; set; }
}
