// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SendCommandRequest
/// Discriminator: type = "sendCommand"
/// Source: webview-messages.ts
/// </summary>
public class SendCommandRequest
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "sendCommand";
    [JsonProperty("command")]
    public string Command { get; set; }
    [JsonProperty("arguments")]
    public string Arguments { get; set; }
    [JsonProperty("messageID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? MessageID { get; set; }
    [JsonProperty("sessionID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? SessionID { get; set; }
    [JsonProperty("draftID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? DraftID { get; set; }
    [JsonProperty("providerID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? ProviderID { get; set; }
    [JsonProperty("modelID", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? ModelID { get; set; }
    [JsonProperty("agent", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Agent { get; set; }
    [JsonProperty("variant", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Variant { get; set; }
    [JsonProperty("files", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | Array
    public object? Files { get; set; }
    [JsonProperty("agentManagerContext", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? AgentManagerContext { get; set; }
    [JsonProperty("contextDirectory", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? ContextDirectory { get; set; }
}
