// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SetWorkStyleMessage
/// Discriminator: type = "setWorkStyle"
/// Source: webview-messages.ts
/// </summary>
public class SetWorkStyleMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "setWorkStyle";
    [JsonProperty("style")]
    // Original TypeScript type: literal
    public string Style { get; set; }
}
