// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SpeechToTextErrorMessage
/// Discriminator: type = "speechToTextError"
/// Source: extension-messages.ts
/// </summary>
public class SpeechToTextErrorMessage
{
    [JsonProperty("type")]
    public string Type { get; set; }
    [JsonProperty("error")]
    public string Error { get; set; }
    [JsonProperty("code", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Code { get; set; }
    [JsonProperty("requestId")]
    public string RequestId { get; set; }
}
