// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SpeechToTextStartMessage
/// Discriminator: type = "speechToTextStart"
/// Source: webview-messages.ts
/// </summary>
public class SpeechToTextStartMessage
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "speechToTextStart";
    [JsonProperty("requestId")]
    public string RequestId { get; set; }
    [JsonProperty("model")]
    public string Model { get; set; }
    [JsonProperty("language", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? Language { get; set; }
}
