// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: StepStartPart
/// Discriminator: type = "step-start"
/// Source: parts.ts
/// </summary>
public class StepStartPart
{
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "step-start";
    [JsonProperty("time", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | __type
    public object? Time { get; set; }
}
