// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: StepFinishPart
/// Discriminator: type = "step-finish"
/// Source: ..\..\..\..\..\sdk\js\src\gen\types.gen.ts
/// </summary>
public class StepFinishPart
{
    [JsonProperty("id")]
    public string Id { get; set; }
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
    [JsonProperty("messageID")]
    public string MessageID { get; set; }
    [JsonProperty("type")]
    // Original TypeScript type: unknown
    public string Type { get; set; } = "step-finish";
    [JsonProperty("reason")]
    public string Reason { get; set; }
    [JsonProperty("snapshot", NullValueHandling = NullValueHandling.Ignore)]
    public string? Snapshot { get; set; }
    [JsonProperty("cost")]
    public double Cost { get; set; }
    [JsonProperty("tokens")]
    public object Tokens { get; set; }
}
