// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SymbolSource
/// Discriminator: type = "symbol"
/// Source: ..\..\..\..\..\sdk\js\src\v2\gen\types.gen.ts
/// </summary>
public class SymbolSource
{
    [JsonProperty("text")]
    public object Text { get; set; }
    [JsonProperty("type")]
    public object Type { get; set; }
    [JsonProperty("path")]
    public string Path { get; set; }
    [JsonProperty("range")]
    public object Range { get; set; }
    [JsonProperty("name")]
    public string Name { get; set; }
    [JsonProperty("kind")]
    public double Kind { get; set; }
}
