// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SyncEventSessionNextRetried
/// Discriminator: type = "sync"
/// Source: ..\..\..\..\..\sdk\js\src\v2\gen\types.gen.ts
/// </summary>
public class SyncEventSessionNextRetried
{
    [JsonProperty("type")]
    // Original TypeScript type: unknown
    public string Type { get; set; } = "sync";
    [JsonProperty("id")]
    public string Id { get; set; }
    [JsonProperty("syncEvent")]
    public object SyncEvent { get; set; }
}
