// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: SystemChatMessage
/// Discriminator: role = "system"
/// Source: ..\..\..\..\src\services\autocomplete\continuedev\core\index.d.ts
/// </summary>
public class SystemChatMessage
{
    [JsonProperty("role")]
    // Original TypeScript type: literal
    public string Role { get; set; } = "system";
    [JsonProperty("content")]
    public string Content { get; set; }
}
