// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: TestDequeue
/// Discriminator: type = "suite"
/// Source: ..\..\..\..\..\kilo-visualstudio\tools\webview-contract-extractor\node_modules\@types\node\test.d.ts
/// </summary>
public class TestDequeue
{
    [JsonProperty("name")]
    public string Name { get; set; }
    [JsonProperty("nesting")]
    public double Nesting { get; set; }
    [JsonProperty("tags")]
    public List<string> Tags { get; set; }
    [JsonProperty("testId")]
    public double TestId { get; set; }
    public string Type { get; set; }
}
