// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: TextPartInput
/// Discriminator: type = "text"
/// Source: ..\..\..\..\..\sdk\js\src\v2\gen\types.gen.ts
/// </summary>
public class TextPartInput
{
    [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
    public string? Id { get; set; }
    [JsonProperty("type")]
    // Original TypeScript type: unknown
    public string Type { get; set; } = "text";
    [JsonProperty("text")]
    public string Text { get; set; }
    [JsonProperty("synthetic", NullValueHandling = NullValueHandling.Ignore)]
    public object? Synthetic { get; set; }
    [JsonProperty("ignored", NullValueHandling = NullValueHandling.Ignore)]
    public object? Ignored { get; set; }
    [JsonProperty("time", NullValueHandling = NullValueHandling.Ignore)]
    public object? Time { get; set; }
    [JsonProperty("metadata", NullValueHandling = NullValueHandling.Ignore)]
    public object? Metadata { get; set; }
}
