// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ToggleSandboxMessage
/// Discriminator: type = "toggleSandbox"
/// Source: webview-messages.ts
/// </summary>
public class ToggleSandboxMessage
{
    [JsonProperty("type")]
    public string Type { get; set; }
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
    [JsonProperty("requestID")]
    public string RequestID { get; set; }
    [JsonProperty("agentManagerContext", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? AgentManagerContext { get; set; }
    [JsonProperty("contextDirectory", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: undefined | string
    public string? ContextDirectory { get; set; }
}
