// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ToolPart
/// Discriminator: type = "tool"
/// Source: ..\..\..\..\..\sdk\js\src\gen\types.gen.ts
/// </summary>
public class ToolPart
{
    [JsonProperty("id")]
    public string Id { get; set; }
    [JsonProperty("sessionID")]
    public string SessionID { get; set; }
    [JsonProperty("messageID")]
    public string MessageID { get; set; }
    [JsonProperty("type")]
    // Original TypeScript type: unknown
    public string Type { get; set; } = "tool";
    [JsonProperty("callID")]
    public string CallID { get; set; }
    [JsonProperty("tool")]
    public string Tool { get; set; }
    [JsonProperty("state", NullValueHandling = NullValueHandling.Ignore)]
    public object? State { get; set; }
    [JsonProperty("metadata", NullValueHandling = NullValueHandling.Ignore)]
    public object? Metadata { get; set; }
}
