// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: ToolAttachment
/// Discriminator: type = "file"
/// Source: ..\..\..\..\..\plugin\src\tool.ts
/// </summary>
public class ToolAttachment
{
    [JsonProperty("type")]
    // Original TypeScript type: unknown
    public string Type { get; set; } = "file";
    [JsonProperty("mime")]
    public string Mime { get; set; }
    [JsonProperty("url")]
    public string Url { get; set; }
    [JsonProperty("filename", NullValueHandling = NullValueHandling.Ignore)]
    public string? Filename { get; set; }
}
