// <auto-generated>
//     This code was generated by WebViewContractGenerator.
//     Do not modify this file directly as changes will be lost on regeneration.
//     Source: WebViewContract.json schema version 1.0.0
// </auto-generated>

#nullable enable

namespace KiloVisualStudioExtension.WebView.Generated;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Newtonsoft.Json;

/// <summary>
/// WebView message: WakeLockSentinel
/// Discriminator: type = "screen"
/// Source: ..\..\..\..\..\kilo-visualstudio\tools\webview-contract-extractor\node_modules\typescript\lib\lib.dom.d.ts
/// </summary>
public class WakeLockSentinel
{
    [JsonProperty("onrelease", NullValueHandling = NullValueHandling.Ignore)]
    // Original TypeScript type: null | __type
    public object? Onrelease { get; set; }
    [JsonProperty("released")]
    // Original TypeScript type: literal
    public string Released { get; set; }
    [JsonProperty("type")]
    // Original TypeScript type: literal
    public string Type { get; set; } = "screen";
}
